# Generated by Django 4.2.17 on 2025-11-13 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_host', models.CharField(default='smtp.gmail.com', max_length=255)),
                ('email_port', models.IntegerField(default=587)),
                ('email_use_tls', models.BooleanField(default=True)),
                ('email_host_user', models.EmailField(blank=True, max_length=255, null=True)),
                ('email_host_password', models.CharField(blank=True, max_length=255, null=True)),
                ('default_from_email', models.CharField(blank=True, max_length=255, null=True)),
                ('email_from_name', models.CharField(blank=True, help_text="Display name for email sender (e.g., 'Your Company Name')", max_length=255, null=True)),
                ('access_token_lifetime_minutes', models.IntegerField(default=60)),
                ('refresh_token_lifetime_days', models.IntegerField(default=1)),
                ('rotate_refresh_tokens', models.BooleanField(default=True)),
                ('blacklist_after_rotation', models.BooleanField(default=True)),
                ('backup_custom_path', models.CharField(blank=True, help_text='Custom directory path for database backups', max_length=500, null=True)),
                ('backup_schedule_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', help_text='Frequency of automatic backups', max_length=20)),
                ('backup_retention_days', models.IntegerField(default=30, help_text='Number of days to keep backups before automatic deletion')),
                ('quota_carry_over_policy', models.CharField(choices=[('independent', 'Independent Quarters'), ('auto', 'Auto Carry Deficit'), ('manual', 'Manual Adjustment')], default='independent', help_text='Policy for carrying over deficit to next quarter', max_length=20)),
                ('quota_carry_over_enabled', models.BooleanField(default=False, help_text='Enable carry-over of deficit amounts between quarters')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'System Configuration',
                'verbose_name_plural': 'System Configurations',
            },
        ),
    ]
