# Generated by Django 4.2.17 on 2025-11-02 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfiguration',
            name='backup_retention_days',
            field=models.IntegerField(default=30, help_text='Number of days to keep backups before automatic deletion'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='backup_schedule_frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', help_text='Frequency of automatic backups', max_length=20),
        ),
    ]
