# Generated by Django 4.2.24 on 2025-10-01 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_config', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemconfiguration',
            name='default_user_password',
        ),
    ]
