# Generated by Django 4.2.24 on 2025-10-01 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_config', '0002_remove_systemconfiguration_default_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemconfiguration',
            name='default_from_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
