# Generated by Django 4.2.24 on 2025-10-02 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_config', '0003_change_default_from_email_field_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfiguration',
            name='password_max_length',
            field=models.IntegerField(default=8, help_text='Maximum password length (6-8)'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='password_min_length',
            field=models.IntegerField(default=6, help_text='Minimum password length (6-8)'),
        ),
    ]
