# Generated by Django 4.2.24 on 2025-10-02 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_config', '0004_systemconfiguration_password_max_length_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemconfiguration',
            name='password_max_length',
        ),
        migrations.RemoveField(
            model_name='systemconfiguration',
            name='password_min_length',
        ),
    ]
