# Generated by Django 5.2.5 on 2025-09-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
