# Generated by Django 4.2.17 on 2025-10-18 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('law', models.CharField(default='PD-1586', help_text='Law code (e.g., PD-1586, RA-6969, RA-8749, RA-9275, RA-9003)', max_length=50)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('current_status', models.CharField(choices=[('CREATED', 'Created'), ('SECTION_ASSIGNED', 'Section Assigned'), ('SECTION_IN_PROGRESS', 'Section In Progress'), ('SECTION_COMPLETED_COMPLIANT', 'Section Completed - Compliant'), ('SECTION_COMPLETED_NON_COMPLIANT', 'Section Completed - Non-Compliant'), ('UNIT_ASSIGNED', 'Unit Assigned'), ('UNIT_IN_PROGRESS', 'Unit In Progress'), ('UNIT_COMPLETED_COMPLIANT', 'Unit Completed - Compliant'), ('UNIT_COMPLETED_NON_COMPLIANT', 'Unit Completed - Non-Compliant'), ('MONITORING_ASSIGNED', 'Monitoring Assigned'), ('MONITORING_IN_PROGRESS', 'Monitoring In Progress'), ('MONITORING_COMPLETED_COMPLIANT', 'Monitoring Completed - Compliant'), ('MONITORING_COMPLETED_NON_COMPLIANT', 'Monitoring Completed - Non-Compliant'), ('UNIT_REVIEWED', 'Unit Reviewed'), ('SECTION_REVIEWED', 'Section Reviewed'), ('DIVISION_REVIEWED', 'Division Reviewed'), ('LEGAL_REVIEW', 'Legal Review'), ('NOV_SENT', 'NOV Sent'), ('NOO_SENT', 'NOO Sent'), ('CLOSED_COMPLIANT', 'Closed - Compliant'), ('CLOSED_NON_COMPLIANT', 'Closed - Non-Compliant')], default='CREATED', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InspectionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='inspections/documents/%Y/%m/%d/')),
                ('document_type', models.CharField(choices=[('REPORT', 'Inspection Report'), ('PHOTO', 'Photo Evidence'), ('PERMIT', 'Permit/License'), ('NOTICE', 'Notice'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='InspectionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(blank=True, max_length=40, null=True)),
                ('new_status', models.CharField(max_length=40)),
                ('law', models.CharField(blank=True, help_text='Law code at the time of change', max_length=50, null=True)),
                ('section', models.CharField(blank=True, help_text='Section at the time of change', max_length=50, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Inspection Histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InspectionForm',
            fields=[
                ('inspection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='form', serialize=False, to='inspections.inspection')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('checklist', models.JSONField(blank=True, default=dict)),
                ('findings_summary', models.TextField(blank=True)),
                ('compliance_decision', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLIANT', 'Compliant'), ('NON_COMPLIANT', 'Non-Compliant'), ('PARTIALLY_COMPLIANT', 'Partially Compliant')], default='PENDING', max_length=30)),
                ('violations_found', models.TextField(blank=True, help_text='List of violations if non-compliant')),
                ('compliance_plan', models.TextField(blank=True, help_text='Establishment compliance plan')),
                ('compliance_deadline', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
