# Generated by Django 4.2.17 on 2025-11-13 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inspections', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('establishments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarterlyevaluation',
            name='evaluated_by',
            field=models.ForeignKey(blank=True, help_text='User who evaluated this quarter', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspectionhistory',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='User the inspection was assigned to at this point', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_assignments_tracked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspectionhistory',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspectionhistory',
            name='inspection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='inspections.inspection'),
        ),
        migrations.AddField(
            model_name='inspectiondocument',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_inspection_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspection',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Current assignee', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections_assigned_new', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspection',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections_created_new', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspection',
            name='establishments',
            field=models.ManyToManyField(related_name='inspections_new', to='establishments.establishment'),
        ),
        migrations.AddField(
            model_name='compliancequota',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this quota', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='billingrecord',
            name='establishment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_records', to='establishments.establishment'),
        ),
        migrations.AddField(
            model_name='billingrecord',
            name='inspection',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_record', to='inspections.inspection'),
        ),
        migrations.AddField(
            model_name='billingrecord',
            name='issued_by',
            field=models.ForeignKey(help_text='User who issued this billing (typically Legal Unit)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_billings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='NoticeOfOrder',
            fields=[
                ('inspection_form', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='noo', serialize=False, to='inspections.inspectionform')),
                ('sent_date', models.DateField(blank=True, help_text='Date NOO was sent', null=True)),
                ('violation_breakdown', models.TextField(blank=True, help_text='Detailed breakdown of violations for NOO')),
                ('penalty_fees', models.DecimalField(blank=True, decimal_places=2, help_text='Total penalty fees assessed', max_digits=10, null=True)),
                ('payment_deadline', models.DateField(blank=True, help_text='Deadline for penalty payment', null=True)),
                ('payment_instructions', models.TextField(blank=True, help_text='Instructions for paying penalties')),
                ('remarks', models.TextField(blank=True, help_text='Additional remarks for NOO')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notice of Order',
                'verbose_name_plural': 'Notices of Order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NoticeOfViolation',
            fields=[
                ('inspection_form', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='nov', serialize=False, to='inspections.inspectionform')),
                ('sent_date', models.DateField(blank=True, help_text='Date NOV was sent', null=True)),
                ('compliance_deadline', models.DateTimeField(blank=True, help_text='Deadline for establishment to comply with NOV', null=True)),
                ('violations', models.TextField(blank=True, help_text='Detailed list of violations found')),
                ('compliance_instructions', models.TextField(blank=True, help_text='Required compliance actions for establishment')),
                ('remarks', models.TextField(blank=True, help_text='Additional remarks for NOV')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notice of Violation',
                'verbose_name_plural': 'Notices of Violation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='reinspectionschedule',
            index=models.Index(fields=['due_date'], name='inspections_due_dat_b20564_idx'),
        ),
        migrations.AddIndex(
            model_name='reinspectionschedule',
            index=models.Index(fields=['status'], name='inspections_status_dc1c70_idx'),
        ),
        migrations.AddIndex(
            model_name='reinspectionschedule',
            index=models.Index(fields=['establishment'], name='inspections_establi_102cfd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reinspectionschedule',
            unique_together={('establishment', 'original_inspection')},
        ),
        migrations.AddIndex(
            model_name='quarterlyevaluation',
            index=models.Index(fields=['law', 'year', 'quarter'], name='inspections_law_f4ff83_idx'),
        ),
        migrations.AddIndex(
            model_name='quarterlyevaluation',
            index=models.Index(fields=['year', 'quarter'], name='inspections_year_8605f9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='quarterlyevaluation',
            unique_together={('law', 'year', 'quarter')},
        ),
        migrations.AddIndex(
            model_name='inspectionhistory',
            index=models.Index(fields=['inspection', '-created_at'], name='inspections_inspect_478b05_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectionhistory',
            index=models.Index(fields=['changed_by'], name='inspections_changed_7ba279_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectionhistory',
            index=models.Index(fields=['assigned_to'], name='inspections_assigne_eafdf9_idx'),
        ),
        migrations.AddField(
            model_name='inspectionform',
            name='inspected_by',
            field=models.ForeignKey(blank=True, help_text='User who first filled out this inspection form', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections_inspected', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspectiondocument',
            name='inspection_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='inspections.inspectionform'),
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['code'], name='inspections_code_dc1b07_idx'),
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['current_status'], name='inspections_current_6b932e_idx'),
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['assigned_to'], name='inspections_assigne_306954_idx'),
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['created_by'], name='inspections_created_282730_idx'),
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['law'], name='inspections_law_e1febf_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancequota',
            index=models.Index(fields=['law', 'year', 'month'], name='inspections_law_a15f50_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancequota',
            index=models.Index(fields=['year', 'month'], name='inspections_year_ffa421_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancequota',
            index=models.Index(fields=['year', 'quarter'], name='inspections_year_ead5b8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='compliancequota',
            unique_together={('law', 'year', 'month')},
        ),
        migrations.AddIndex(
            model_name='billingrecord',
            index=models.Index(fields=['billing_code'], name='inspections_billing_c5e0c5_idx'),
        ),
        migrations.AddIndex(
            model_name='billingrecord',
            index=models.Index(fields=['establishment'], name='inspections_establi_edae83_idx'),
        ),
        migrations.AddIndex(
            model_name='billingrecord',
            index=models.Index(fields=['-created_at'], name='inspections_created_9b7da4_idx'),
        ),
        migrations.AddIndex(
            model_name='billingrecord',
            index=models.Index(fields=['related_law'], name='inspections_related_d892c1_idx'),
        ),
        migrations.AddField(
            model_name='noticeofviolation',
            name='sent_by',
            field=models.ForeignKey(blank=True, help_text='User who sent this NOV', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nov_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='noticeoforder',
            name='sent_by',
            field=models.ForeignKey(blank=True, help_text='User who sent this NOO', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='noo_sent', to=settings.AUTH_USER_MODEL),
        ),
    ]
