# Generated by Django 4.2.24 on 2025-10-04 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inspections', '0001_initial'),
        ('establishments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionhistory',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspectionhistory',
            name='inspection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='inspections.inspection'),
        ),
        migrations.AddField(
            model_name='inspectiondocument',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_inspection_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspection',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Current assignee', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections_assigned_new', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspection',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections_created_new', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspection',
            name='establishments',
            field=models.ManyToManyField(related_name='inspections_new', to='establishments.establishment'),
        ),
        migrations.AddField(
            model_name='inspectiondocument',
            name='inspection_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='inspections.inspectionform'),
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['current_status'], name='inspections_current_6b932e_idx'),
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['assigned_to'], name='inspections_assigne_306954_idx'),
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['created_by'], name='inspections_created_282730_idx'),
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['law'], name='inspections_law_e1febf_idx'),
        ),
    ]
