# Generated by Django 4.2.17 on 2025-11-13 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticeoforder',
            name='contact_person',
            field=models.CharField(blank=True, help_text='Contact person included in NOO', max_length=255),
        ),
        migrations.AddField(
            model_name='noticeoforder',
            name='email_body',
            field=models.TextField(blank=True, help_text='Body content sent for NOO email'),
        ),
        migrations.AddField(
            model_name='noticeoforder',
            name='email_subject',
            field=models.CharField(blank=True, help_text='Subject used for NOO email', max_length=255),
        ),
        migrations.AddField(
            model_name='noticeoforder',
            name='recipient_email',
            field=models.EmailField(blank=True, help_text='Email address used when sending NOO', max_length=254),
        ),
        migrations.AddField(
            model_name='noticeoforder',
            name='recipient_name',
            field=models.CharField(blank=True, help_text='Recipient name for NOO email', max_length=255),
        ),
        migrations.AddField(
            model_name='noticeofviolation',
            name='contact_person',
            field=models.CharField(blank=True, help_text='Contact person included in NOV', max_length=255),
        ),
        migrations.AddField(
            model_name='noticeofviolation',
            name='email_body',
            field=models.TextField(blank=True, help_text='Body content sent for NOV email'),
        ),
        migrations.AddField(
            model_name='noticeofviolation',
            name='email_subject',
            field=models.CharField(blank=True, help_text='Subject used for NOV email', max_length=255),
        ),
        migrations.AddField(
            model_name='noticeofviolation',
            name='recipient_email',
            field=models.EmailField(blank=True, help_text='Email address used when sending NOV', max_length=254),
        ),
        migrations.AddField(
            model_name='noticeofviolation',
            name='recipient_name',
            field=models.CharField(blank=True, help_text='Recipient name for NOV email', max_length=255),
        ),
    ]
