# Generated by Django 4.2.17 on 2025-10-18 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('establishments', '0001_initial'),
        ('inspections', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionform',
            name='noo_payment_deadline',
            field=models.DateField(blank=True, help_text='Deadline for penalty payment', null=True),
        ),
        migrations.AddField(
            model_name='inspectionform',
            name='noo_payment_instructions',
            field=models.TextField(blank=True, help_text='Instructions for paying penalties'),
        ),
        migrations.AddField(
            model_name='inspectionform',
            name='noo_penalty_fees',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total penalty fees assessed', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='inspectionform',
            name='noo_remarks',
            field=models.TextField(blank=True, help_text='Additional remarks for NOO'),
        ),
        migrations.AddField(
            model_name='inspectionform',
            name='noo_sent_date',
            field=models.DateField(blank=True, help_text='Date NOO was sent', null=True),
        ),
        migrations.AddField(
            model_name='inspectionform',
            name='noo_violation_breakdown',
            field=models.TextField(blank=True, help_text='Detailed breakdown of violations for NOO'),
        ),
        migrations.AddField(
            model_name='inspectionform',
            name='nov_compliance_date',
            field=models.DateTimeField(blank=True, help_text='Deadline for establishment to comply with NOV', null=True),
        ),
        migrations.AddField(
            model_name='inspectionform',
            name='nov_compliance_instructions',
            field=models.TextField(blank=True, help_text='Required compliance actions for establishment'),
        ),
        migrations.AddField(
            model_name='inspectionform',
            name='nov_remarks',
            field=models.TextField(blank=True, help_text='Additional remarks for NOV'),
        ),
        migrations.AddField(
            model_name='inspectionform',
            name='nov_sent_date',
            field=models.DateField(blank=True, help_text='Date NOV was sent', null=True),
        ),
        migrations.AddField(
            model_name='inspectionform',
            name='nov_violations',
            field=models.TextField(blank=True, help_text='Detailed list of violations found'),
        ),
        migrations.CreateModel(
            name='BillingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_code', models.CharField(help_text='Format: BILL-YYYY-NNNN', max_length=30, unique=True)),
                ('establishment_name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(blank=True, max_length=255)),
                ('contact_number', models.CharField(blank=True, max_length=50)),
                ('related_law', models.CharField(max_length=50)),
                ('billing_type', models.CharField(choices=[('PENALTY', 'Penalty'), ('FEE', 'Fee'), ('FINE', 'Fine')], default='PENALTY', max_length=20)),
                ('description', models.TextField(help_text='Detailed description of billing reason')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Total billing amount', max_digits=10)),
                ('due_date', models.DateField(help_text='Payment deadline')),
                ('recommendations', models.TextField(blank=True, help_text='Additional recommendations or instructions')),
                ('sent_date', models.DateTimeField(auto_now_add=True, help_text='When billing was created and sent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_records', to='establishments.establishment')),
                ('inspection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_record', to='inspections.inspection')),
                ('issued_by', models.ForeignKey(help_text='User who issued this billing (typically Legal Unit)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_billings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Billing Record',
                'verbose_name_plural': 'Billing Records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BillingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation', models.CharField(help_text='Description of specific violation', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Penalty amount for this violation', max_digits=10)),
                ('order', models.IntegerField(default=0, help_text='Display order (for sorting line items)')),
                ('billing_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inspections.billingrecord')),
            ],
            options={
                'verbose_name': 'Billing Item',
                'verbose_name_plural': 'Billing Items',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='billingrecord',
            index=models.Index(fields=['billing_code'], name='inspections_billing_c5e0c5_idx'),
        ),
        migrations.AddIndex(
            model_name='billingrecord',
            index=models.Index(fields=['establishment'], name='inspections_establi_edae83_idx'),
        ),
        migrations.AddIndex(
            model_name='billingrecord',
            index=models.Index(fields=['-created_at'], name='inspections_created_9b7da4_idx'),
        ),
        migrations.AddIndex(
            model_name='billingrecord',
            index=models.Index(fields=['related_law'], name='inspections_related_d892c1_idx'),
        ),
    ]
