# Generated by Django 4.2.24 on 2025-10-08 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='current_status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('SECTION_ASSIGNED', 'Section Assigned'), ('SECTION_IN_PROGRESS', 'Section In Progress'), ('SECTION_COMPLETED_COMPLIANT', 'Section Completed - Compliant'), ('SECTION_COMPLETED_NON_COMPLIANT', 'Section Completed - Non-Compliant'), ('UNIT_ASSIGNED', 'Unit Assigned'), ('UNIT_IN_PROGRESS', 'Unit In Progress'), ('UNIT_COMPLETED_COMPLIANT', 'Unit Completed - Compliant'), ('UNIT_COMPLETED_NON_COMPLIANT', 'Unit Completed - Non-Compliant'), ('MONITORING_ASSIGNED', 'Monitoring Assigned'), ('MONITORING_IN_PROGRESS', 'Monitoring In Progress'), ('MONITORING_COMPLETED_COMPLIANT', 'Monitoring Completed - Compliant'), ('MONITORING_COMPLETED_NON_COMPLIANT', 'Monitoring Completed - Non-Compliant'), ('UNIT_REVIEWED', 'Unit Reviewed'), ('SECTION_REVIEWED', 'Section Reviewed'), ('DIVISION_REVIEWED', 'Division Reviewed'), ('LEGAL_REVIEW', 'Legal Review'), ('NOV_SENT', 'NOV Sent'), ('NOO_SENT', 'NOO Sent'), ('FINALIZED', 'Finalized'), ('CLOSED', 'Closed'), ('CLOSED_COMPLIANT', 'Closed - Compliant'), ('CLOSED_NON_COMPLIANT', 'Closed - Non-Compliant')], default='CREATED', max_length=40),
        ),
    ]
