# Generated by Django 5.2.1 on 2025-09-25 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0002_inspection_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='applicable_laws',
            field=models.TextField(blank=True, help_text='Applicable laws and regulations', null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='assigned_division_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='division_head_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspection',
            name='assigned_legal_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legal_unit_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspection',
            name='billing_record',
            field=models.TextField(blank=True, help_text='Billing record created by legal unit', null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='compliance_call',
            field=models.TextField(blank=True, help_text='Compliance call details', null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='current_assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_inspection_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspection',
            name='inspection_list',
            field=models.TextField(blank=True, help_text='List of inspections to be conducted', null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='inspection_notes',
            field=models.TextField(blank=True, help_text='Inspection notes and findings', null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='workflow_comments',
            field=models.TextField(blank=True, help_text='Comments from current reviewer', null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('LEGAL_REVIEW', 'Legal Review'), ('DIVISION_CREATED', 'Division Created'), ('SECTION_REVIEW', 'Section Review'), ('UNIT_REVIEW', 'Unit Review'), ('MONITORING_INSPECTION', 'Monitoring Inspection'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=30),
        ),
    ]
