# Generated by Django 4.2.17 on 2025-10-27 22:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0001_initial'),
        ('inspections', '0003_initialize_default_quotas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReinspectionSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compliance_status', models.CharField(choices=[('COMPLIANT', 'Compliant'), ('NON_COMPLIANT', 'Non-Compliant')], max_length=20)),
                ('due_date', models.DateField()),
                ('reminder_sent', models.BooleanField(default=False)),
                ('reminder_sent_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reinspection_schedules', to='establishments.establishment')),
                ('original_inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reinspection_schedules', to='inspections.inspection')),
            ],
            options={
                'ordering': ['due_date'],
                'indexes': [models.Index(fields=['due_date'], name='inspections_reinspection_due_date_idx'), models.Index(fields=['status'], name='inspections_reinspection_status_idx'), models.Index(fields=['establishment'], name='inspections_reinspection_establishment_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='reinspectionschedule',
            constraint=models.UniqueConstraint(fields=('establishment', 'original_inspection'), name='inspections_reinspection_unique_establishment_inspection'),
        ),
    ]
