# Generated by Django 4.2.24 on 2025-10-02 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inspections', '0003_inspection_applicable_laws_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='section_chief_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='section_chief_decision',
            field=models.CharField(blank=True, choices=[('INSPECT', 'Inspect'), ('FORWARD', 'Forward'), ('COMPLETE', 'Complete'), ('REJECT', 'Reject')], help_text="Section Chief's decision", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='section_chief_decision_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='unit_head_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='unit_head_decision',
            field=models.CharField(blank=True, choices=[('INSPECT', 'Inspect'), ('FORWARD', 'Forward'), ('COMPLETE', 'Complete'), ('REJECT', 'Reject')], help_text="Unit Head's decision", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='unit_head_decision_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('LEGAL_REVIEW', 'Legal Review'), ('DIVISION_CREATED', 'Division Created'), ('SECTION_REVIEW', 'Section Review'), ('SECTION_INSPECTING', 'Section Inspecting'), ('UNIT_REVIEW', 'Unit Review'), ('UNIT_INSPECTING', 'Unit Inspecting'), ('MONITORING_INSPECTION', 'Monitoring Inspection'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=30),
        ),
        migrations.CreateModel(
            name='InspectionWorkflowHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('INSPECT', 'Inspect'), ('FORWARD', 'Forward'), ('COMPLETE', 'Complete'), ('REJECT', 'Reject')], max_length=20)),
                ('comments', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_history', to='inspections.inspection')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inspection Workflow History',
                'verbose_name_plural': 'Inspection Workflow Histories',
                'ordering': ['-timestamp'],
            },
        ),
    ]
