# Generated by Django 4.2.17 on 2025-10-18 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inspections', '0003_inspectionform_noo_payment_deadline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=10)),
                ('payment_date', models.DateField(help_text='Date when payment was made')),
                ('notes', models.TextField(blank=True, help_text='Payment notes or comments')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this payment record was created')),
            ],
            options={
                'verbose_name': 'Payment History',
                'verbose_name_plural': 'Payment Histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='billingrecord',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total amount paid so far', max_digits=10),
        ),
        migrations.AddField(
            model_name='billingrecord',
            name='payment_date',
            field=models.DateField(blank=True, help_text='Date when payment was made', null=True),
        ),
        migrations.AddField(
            model_name='billingrecord',
            name='payment_method',
            field=models.CharField(blank=True, help_text='Method of payment (Cash, Check, Bank Transfer, etc.)', max_length=50),
        ),
        migrations.AddField(
            model_name='billingrecord',
            name='payment_notes',
            field=models.TextField(blank=True, help_text='Additional payment notes'),
        ),
        migrations.AddField(
            model_name='billingrecord',
            name='payment_reference',
            field=models.CharField(blank=True, help_text='Payment reference number or check number', max_length=100),
        ),
        migrations.AddField(
            model_name='billingrecord',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIAL', 'Partially Paid'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('WAIVED', 'Waived')], default='UNPAID', help_text='Current payment status', max_length=20),
        ),
        migrations.AddIndex(
            model_name='billingrecord',
            index=models.Index(fields=['payment_status'], name='inspections_payment_7c2a4c_idx'),
        ),
        migrations.AddIndex(
            model_name='billingrecord',
            index=models.Index(fields=['due_date'], name='inspections_due_dat_2915a9_idx'),
        ),
        migrations.AddIndex(
            model_name='billingrecord',
            index=models.Index(fields=['payment_status', 'due_date'], name='inspections_payment_663af2_idx'),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='billing_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_history', to='inspections.billingrecord'),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='recorded_by',
            field=models.ForeignKey(help_text='User who recorded this payment', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='paymenthistory',
            index=models.Index(fields=['billing_record', '-created_at'], name='inspections_billing_952851_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenthistory',
            index=models.Index(fields=['payment_date'], name='inspections_payment_3ef519_idx'),
        ),
    ]
