# Generated by Django 4.2.17 on 2025-10-11 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inspections', '0003_alter_inspection_current_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionform',
            name='first_filled_at',
            field=models.DateTimeField(blank=True, help_text='When the form was first filled out', null=True),
        ),
        migrations.AddField(
            model_name='inspectionform',
            name='first_filled_by',
            field=models.ForeignKey(blank=True, help_text='User who first filled out this inspection form', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections_first_filled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspectionform',
            name='first_filled_by_district',
            field=models.CharField(blank=True, help_text='District when form was first filled', max_length=100),
        ),
        migrations.AddField(
            model_name='inspectionform',
            name='first_filled_by_level',
            field=models.CharField(blank=True, help_text='User level when form was first filled', max_length=50),
        ),
        migrations.AddField(
            model_name='inspectionform',
            name='first_filled_by_section',
            field=models.CharField(blank=True, help_text='Section when form was first filled', max_length=50),
        ),
    ]
