# Generated by Django 4.2.17 on 2025-10-11 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0004_inspectionform_first_filled_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspectionform',
            name='first_filled_by_district',
        ),
        migrations.RemoveField(
            model_name='inspectionform',
            name='first_filled_by_level',
        ),
    ]
