# Generated by Django 4.2.17 on 2025-10-19 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0004_paymenthistory_billingrecord_payment_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenthistory',
            name='billing_record',
        ),
        migrations.RemoveField(
            model_name='paymenthistory',
            name='recorded_by',
        ),
        migrations.RemoveIndex(
            model_name='billingrecord',
            name='inspections_payment_7c2a4c_idx',
        ),
        migrations.RemoveIndex(
            model_name='billingrecord',
            name='inspections_due_dat_2915a9_idx',
        ),
        migrations.RemoveIndex(
            model_name='billingrecord',
            name='inspections_payment_663af2_idx',
        ),
        migrations.RemoveField(
            model_name='billingrecord',
            name='payment_amount',
        ),
        migrations.RemoveField(
            model_name='billingrecord',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='billingrecord',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='billingrecord',
            name='payment_notes',
        ),
        migrations.RemoveField(
            model_name='billingrecord',
            name='payment_reference',
        ),
        migrations.RemoveField(
            model_name='billingrecord',
            name='payment_status',
        ),
        migrations.DeleteModel(
            name='PaymentHistory',
        ),
    ]
