# Generated by Django 4.2.24 on 2025-10-02 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0004_inspection_section_chief_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='section_chief_decision',
            field=models.CharField(blank=True, choices=[('INSPECT', 'Inspect'), ('FORWARD', 'Forward'), ('FORWARD_TO_MONITORING', 'Forward to Monitoring'), ('COMPLETE', 'Complete'), ('REJECT', 'Reject')], help_text="Section Chief's decision", max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='unit_head_decision',
            field=models.CharField(blank=True, choices=[('INSPECT', 'Inspect'), ('FORWARD', 'Forward'), ('FORWARD_TO_MONITORING', 'Forward to Monitoring'), ('COMPLETE', 'Complete'), ('REJECT', 'Reject')], help_text="Unit Head's decision", max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='inspectionworkflowhistory',
            name='action',
            field=models.CharField(choices=[('INSPECT', 'Inspect'), ('FORWARD', 'Forward'), ('FORWARD_TO_MONITORING', 'Forward to Monitoring'), ('COMPLETE', 'Complete'), ('REJECT', 'Reject')], max_length=25),
        ),
    ]
