# Generated by Django 4.2.17 on 2025-11-02 04:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('establishments', '0002_add_marker_icon'),
        ('inspections', '0004_add_reinspection_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('law', models.CharField(help_text='Law code (e.g., PD-1586, RA-6969, RA-8749, RA-9275, RA-9003)', max_length=50)),
                ('year', models.IntegerField(help_text='Year of the quota')),
                ('month', models.IntegerField(help_text='Month (0-11, 0=January)')),
                ('target', models.IntegerField(help_text='Target number of inspections')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['year', 'month', 'law'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='reinspectionschedule',
            name='inspections_reinspection_unique_establishment_inspection',
        ),
        migrations.RenameIndex(
            model_name='reinspectionschedule',
            new_name='inspections_due_dat_b20564_idx',
            old_name='inspections_reinspection_due_date_idx',
        ),
        migrations.RenameIndex(
            model_name='reinspectionschedule',
            new_name='inspections_status_dc1c70_idx',
            old_name='inspections_reinspection_status_idx',
        ),
        migrations.RenameIndex(
            model_name='reinspectionschedule',
            new_name='inspections_establi_102cfd_idx',
            old_name='inspections_reinspection_establishment_idx',
        ),
        migrations.AlterUniqueTogether(
            name='reinspectionschedule',
            unique_together={('establishment', 'original_inspection')},
        ),
        migrations.AddField(
            model_name='monthlyquota',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this quota', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='monthlyquota',
            index=models.Index(fields=['law', 'year', 'month'], name='inspections_law_606997_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlyquota',
            index=models.Index(fields=['year', 'month'], name='inspections_year_ea59f4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='monthlyquota',
            unique_together={('law', 'year', 'month')},
        ),
    ]
