# Generated by Django 4.2.17 on 2025-11-02 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0005_monthlyquota_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MonthlyQuota',
        ),
    ]
