# Generated by Django 4.2.17 on 2025-11-15 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0005_billingrecord_unpaid_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingrecord',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('PAID', 'Paid')], default='UNPAID', help_text='Current payment status', max_length=20),
        ),
    ]
