# Generated by Django 4.2.17 on 2025-11-18 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0007_add_legal_action_to_billing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliancequota',
            name='law',
            field=models.CharField(help_text='Law code (e.g., PD-1586, RA-6969) - must match reference_code in Law model', max_length=50),
        ),
    ]
