# Generated by Django 4.2.17 on 2025-11-05 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0007_add_quarterly_evaluation'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='quarterlyevaluation',
            new_name='inspections_law_f4ff83_idx',
            old_name='inspections_law_yea_quarter_idx',
        ),
        migrations.RenameIndex(
            model_name='quarterlyevaluation',
            new_name='inspections_year_8605f9_idx',
            old_name='inspections_year_quarter_idx',
        ),
    ]
