# Generated by Django 4.2.17 on 2025-10-12 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inspections', '0007_remove_inspection_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='current_status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('SECTION_ASSIGNED', 'Section Assigned'), ('SECTION_IN_PROGRESS', 'Section In Progress'), ('SECTION_COMPLETED_COMPLIANT', 'Section Completed - Compliant'), ('SECTION_COMPLETED_NON_COMPLIANT', 'Section Completed - Non-Compliant'), ('UNIT_ASSIGNED', 'Unit Assigned'), ('UNIT_IN_PROGRESS', 'Unit In Progress'), ('UNIT_COMPLETED_COMPLIANT', 'Unit Completed - Compliant'), ('UNIT_COMPLETED_NON_COMPLIANT', 'Unit Completed - Non-Compliant'), ('MONITORING_ASSIGNED', 'Monitoring Assigned'), ('MONITORING_IN_PROGRESS', 'Monitoring In Progress'), ('MONITORING_COMPLETED_COMPLIANT', 'Monitoring Completed - Compliant'), ('MONITORING_COMPLETED_NON_COMPLIANT', 'Monitoring Completed - Non-Compliant'), ('UNIT_REVIEWED', 'Unit Reviewed'), ('SECTION_REVIEWED', 'Section Reviewed'), ('DIVISION_REVIEWED', 'Division Reviewed'), ('LEGAL_REVIEW', 'Legal Review'), ('NOV_SENT', 'NOV Sent'), ('NOO_SENT', 'NOO Sent'), ('CLOSED_COMPLIANT', 'Closed - Compliant'), ('CLOSED_NON_COMPLIANT', 'Closed - Non-Compliant')], default='CREATED', max_length=40),
        ),
        migrations.AlterField(
            model_name='inspectionform',
            name='inspected_by',
            field=models.ForeignKey(blank=True, help_text='User who first filled out this inspection form', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections_inspected', to=settings.AUTH_USER_MODEL),
        ),
    ]
