# Generated by Django 4.2.24 on 2025-10-03 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0007_enhance_inspectionlawassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='section_chief_decision',
            field=models.CharField(blank=True, choices=[('INSPECT', 'Inspect'), ('FORWARD', 'Forward'), ('FORWARD_TO_MONITORING', 'Forward to Monitoring'), ('FORWARD_TO_ANOTHER_SECTION', 'Forward to Another Section'), ('COMPLETE', 'Complete'), ('REJECT', 'Reject')], help_text="Section Chief's decision", max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='unit_head_decision',
            field=models.CharField(blank=True, choices=[('INSPECT', 'Inspect'), ('FORWARD', 'Forward'), ('FORWARD_TO_MONITORING', 'Forward to Monitoring'), ('FORWARD_TO_ANOTHER_SECTION', 'Forward to Another Section'), ('COMPLETE', 'Complete'), ('REJECT', 'Reject')], help_text="Unit Head's decision", max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='inspectionworkflowhistory',
            name='action',
            field=models.CharField(choices=[('INSPECT', 'Inspect'), ('FORWARD', 'Forward'), ('FORWARD_TO_MONITORING', 'Forward to Monitoring'), ('FORWARD_TO_ANOTHER_SECTION', 'Forward to Another Section'), ('COMPLETE', 'Complete'), ('REJECT', 'Reject')], max_length=30),
        ),
    ]
