# Generated by Django 4.2.17 on 2025-10-13 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inspections', '0008_alter_inspection_current_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionhistory',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='User the inspection was assigned to at this point', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_assignments_tracked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspectionhistory',
            name='law',
            field=models.CharField(blank=True, help_text='Law code at the time of change', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='inspectionhistory',
            name='section',
            field=models.CharField(blank=True, help_text='Section at the time of change', max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='inspectionhistory',
            index=models.Index(fields=['inspection', '-created_at'], name='inspections_inspect_478b05_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectionhistory',
            index=models.Index(fields=['changed_by'], name='inspections_changed_7ba279_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectionhistory',
            index=models.Index(fields=['assigned_to'], name='inspections_assigne_eafdf9_idx'),
        ),
    ]
