# Generated by Django 4.2.17 on 2025-10-14 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0009_update_inspection_history'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['code'], name='inspections_code_dc1b07_idx'),
        ),
    ]
