# Generated by Django 4.2.17 on 2025-10-20 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0009_remove_redundant_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionform',
            name='violations_found',
            field=models.TextField(blank=True, help_text='List of violations found during inspection'),
        ),
    ]
