# Generated by Django 4.2.17 on 2025-10-21 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0010_alter_inspectionform_violations_found'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingrecord',
            name='contact_number',
        ),
        migrations.DeleteModel(
            name='BillingItem',
        ),
    ]
