# Generated by Django 4.2.24 on 2025-10-03 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0010_add_compliance_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='section_chief_decision',
            field=models.CharField(blank=True, choices=[('INSPECT', 'Inspect'), ('FORWARD', 'Forward'), ('FORWARD_TO_UNIT', 'Forward to Unit Head'), ('FORWARD_TO_MONITORING', 'Forward to Monitoring'), ('FORWARD_TO_ANOTHER_SECTION', 'Forward to Another Section'), ('FORWARD_TO_MONITORING_PERSONNEL', 'Forward to Monitoring Personnel'), ('COMPLETE', 'Complete'), ('COMPLETE_COMPLIANT', 'Complete - Compliant'), ('COMPLETE_NON_COMPLIANT', 'Complete - Non-Compliant'), ('SEND_NOV', 'Send Notice of Violation'), ('SEND_NOO', 'Send Notice of Order'), ('CLOSE_CASE', 'Close Case'), ('REJECT', 'Reject')], help_text="Section Chief's decision", max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='status',
            field=models.CharField(choices=[('DIVISION_CREATED', 'Division Created'), ('SECTION_REVIEW', 'Section Review'), ('SECTION_INSPECTING', 'Section Inspecting'), ('UNIT_REVIEW', 'Unit Review'), ('UNIT_INSPECTING', 'Unit Inspecting'), ('MONITORING_ASSIGN', 'Monitoring Assignment'), ('MONITORING_INSPECTION', 'Monitoring Inspection'), ('COMPLIANT_COMPLETE', 'Compliant Complete'), ('NON_COMPLIANT_RETURN', 'Non-Compliant Return'), ('LEGAL_REVIEW', 'Legal Review'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='DIVISION_CREATED', max_length=30),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='unit_head_decision',
            field=models.CharField(blank=True, choices=[('INSPECT', 'Inspect'), ('FORWARD', 'Forward'), ('FORWARD_TO_UNIT', 'Forward to Unit Head'), ('FORWARD_TO_MONITORING', 'Forward to Monitoring'), ('FORWARD_TO_ANOTHER_SECTION', 'Forward to Another Section'), ('FORWARD_TO_MONITORING_PERSONNEL', 'Forward to Monitoring Personnel'), ('COMPLETE', 'Complete'), ('COMPLETE_COMPLIANT', 'Complete - Compliant'), ('COMPLETE_NON_COMPLIANT', 'Complete - Non-Compliant'), ('SEND_NOV', 'Send Notice of Violation'), ('SEND_NOO', 'Send Notice of Order'), ('CLOSE_CASE', 'Close Case'), ('REJECT', 'Reject')], help_text="Unit Head's decision", max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='inspectionworkflowhistory',
            name='action',
            field=models.CharField(choices=[('INSPECT', 'Inspect'), ('FORWARD', 'Forward'), ('FORWARD_TO_UNIT', 'Forward to Unit Head'), ('FORWARD_TO_MONITORING', 'Forward to Monitoring'), ('FORWARD_TO_ANOTHER_SECTION', 'Forward to Another Section'), ('FORWARD_TO_MONITORING_PERSONNEL', 'Forward to Monitoring Personnel'), ('COMPLETE', 'Complete'), ('COMPLETE_COMPLIANT', 'Complete - Compliant'), ('COMPLETE_NON_COMPLIANT', 'Complete - Non-Compliant'), ('SEND_NOV', 'Send Notice of Violation'), ('SEND_NOO', 'Send Notice of Order'), ('CLOSE_CASE', 'Close Case'), ('REJECT', 'Reject')], max_length=35),
        ),
    ]
