# Generated by Django 4.2.24 on 2025-10-03 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0011_alter_inspection_section_chief_decision_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='section_chief_decision',
            field=models.CharField(blank=True, choices=[('INSPECT', 'Inspect'), ('START_INSPECTION', 'Start Inspection'), ('COMPLETE_INSPECTION', 'Complete Inspection'), ('FORWARD', 'Forward'), ('FORWARD_TO_UNIT', 'Forward to Unit Head'), ('FORWARD_TO_MONITORING', 'Forward to Monitoring'), ('FORWARD_TO_ANOTHER_SECTION', 'Forward to Another Section'), ('FORWARD_TO_MONITORING_PERSONNEL', 'Forward to Monitoring Personnel'), ('COMPLETE', 'Complete'), ('COMPLETE_COMPLIANT', 'Complete - Compliant'), ('COMPLETE_NON_COMPLIANT', 'Complete - Non-Compliant'), ('REVIEW', 'Review'), ('FORWARD_TO_DIVISION', 'Forward to Division'), ('FORWARD_TO_SECTION', 'Forward to Section'), ('FORWARD_TO_LEGAL', 'Forward to Legal Unit'), ('SEND_NOV', 'Send Notice of Violation'), ('SEND_NOO', 'Send Notice of Order'), ('CLOSE_CASE', 'Close Case'), ('REJECT', 'Reject')], help_text="Section Chief's decision", max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='status',
            field=models.CharField(choices=[('DIVISION_CREATED', 'Division Created'), ('SECTION_ASSIGNED', 'Section Assigned'), ('SECTION_IN_PROGRESS', 'Section In Progress'), ('SECTION_COMPLETED', 'Section Completed'), ('UNIT_ASSIGNED', 'Unit Assigned'), ('UNIT_IN_PROGRESS', 'Unit In Progress'), ('UNIT_COMPLETED', 'Unit Completed'), ('MONITORING_ASSIGN', 'Monitoring Assignment'), ('MONITORING_IN_PROGRESS', 'Monitoring In Progress'), ('MONITORING_COMPLETED_COMPLIANT', 'Monitoring Completed - Compliant'), ('NON_COMPLIANT_RETURN', 'Non-Compliant Return'), ('UNIT_REVIEWED', 'Unit Reviewed'), ('SECTION_REVIEWED', 'Section Reviewed'), ('DIVISION_REVIEWED', 'Division Reviewed'), ('LEGAL_REVIEW', 'Legal Review'), ('NOV_SENT', 'Notice of Violation Sent'), ('NOO_SENT', 'Notice of Order Sent'), ('CLOSED', 'Closed'), ('REJECTED', 'Rejected')], default='DIVISION_CREATED', max_length=30),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='unit_head_decision',
            field=models.CharField(blank=True, choices=[('INSPECT', 'Inspect'), ('START_INSPECTION', 'Start Inspection'), ('COMPLETE_INSPECTION', 'Complete Inspection'), ('FORWARD', 'Forward'), ('FORWARD_TO_UNIT', 'Forward to Unit Head'), ('FORWARD_TO_MONITORING', 'Forward to Monitoring'), ('FORWARD_TO_ANOTHER_SECTION', 'Forward to Another Section'), ('FORWARD_TO_MONITORING_PERSONNEL', 'Forward to Monitoring Personnel'), ('COMPLETE', 'Complete'), ('COMPLETE_COMPLIANT', 'Complete - Compliant'), ('COMPLETE_NON_COMPLIANT', 'Complete - Non-Compliant'), ('REVIEW', 'Review'), ('FORWARD_TO_DIVISION', 'Forward to Division'), ('FORWARD_TO_SECTION', 'Forward to Section'), ('FORWARD_TO_LEGAL', 'Forward to Legal Unit'), ('SEND_NOV', 'Send Notice of Violation'), ('SEND_NOO', 'Send Notice of Order'), ('CLOSE_CASE', 'Close Case'), ('REJECT', 'Reject')], help_text="Unit Head's decision", max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='inspectionworkflowhistory',
            name='action',
            field=models.CharField(choices=[('INSPECT', 'Inspect'), ('START_INSPECTION', 'Start Inspection'), ('COMPLETE_INSPECTION', 'Complete Inspection'), ('FORWARD', 'Forward'), ('FORWARD_TO_UNIT', 'Forward to Unit Head'), ('FORWARD_TO_MONITORING', 'Forward to Monitoring'), ('FORWARD_TO_ANOTHER_SECTION', 'Forward to Another Section'), ('FORWARD_TO_MONITORING_PERSONNEL', 'Forward to Monitoring Personnel'), ('COMPLETE', 'Complete'), ('COMPLETE_COMPLIANT', 'Complete - Compliant'), ('COMPLETE_NON_COMPLIANT', 'Complete - Non-Compliant'), ('REVIEW', 'Review'), ('FORWARD_TO_DIVISION', 'Forward to Division'), ('FORWARD_TO_SECTION', 'Forward to Section'), ('FORWARD_TO_LEGAL', 'Forward to Legal Unit'), ('SEND_NOV', 'Send Notice of Violation'), ('SEND_NOO', 'Send Notice of Order'), ('CLOSE_CASE', 'Close Case'), ('REJECT', 'Reject')], max_length=35),
        ),
    ]
