# Generated by Django 4.2.17 on 2025-10-21 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inspections', '0011_remove_billing_item_and_contact_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('law', models.CharField(help_text='Law code (e.g., PD-1586, RA-6969, RA-8749, RA-9275, RA-9003)', max_length=50)),
                ('year', models.IntegerField(help_text='Year of the quota')),
                ('quarter', models.IntegerField(choices=[(1, 'Q1'), (2, 'Q2'), (3, 'Q3'), (4, 'Q4')], help_text='Quarter 1-4')),
                ('target', models.IntegerField(help_text='Target number of inspections')),
                ('auto_adjusted', models.BooleanField(default=False, help_text='True if auto-set from previous quarter')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this quota', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['year', 'quarter', 'law'],
                'indexes': [models.Index(fields=['law', 'year', 'quarter'], name='inspections_law_bed71c_idx'), models.Index(fields=['year', 'quarter'], name='inspections_year_ead5b8_idx')],
                'unique_together': {('law', 'year', 'quarter')},
            },
        ),
    ]
