# Generated by Django 4.2.17 on 2025-11-05 17:57
# Updated to safely handle indexes that may already exist

from django.db import migrations, models


def safe_remove_index(apps, schema_editor):
    """Safely remove index if it exists"""
    from django.db import connection
    
    index_name = 'inspections_law_bed71c_idx'
    table_name = 'inspections_compliancequota'
    
    with connection.cursor() as cursor:
        if connection.vendor == 'mysql':
            cursor.execute("""
                SELECT COUNT(*) 
                FROM information_schema.STATISTICS 
                WHERE TABLE_SCHEMA = DATABASE() 
                AND TABLE_NAME = %s 
                AND INDEX_NAME = %s
            """, [table_name, index_name])
        else:
            cursor.execute("""
                SELECT COUNT(*) 
                FROM information_schema.STATISTICS 
                WHERE TABLE_NAME = %s 
                AND INDEX_NAME = %s
            """, [table_name, index_name])
        
        index_exists = cursor.fetchone()[0] > 0
        
        if index_exists:
            cursor.execute(f"ALTER TABLE {table_name} DROP INDEX {index_name}")


def safe_add_index(apps, schema_editor, index_name, fields):
    """Safely add index if it doesn't exist"""
    from django.db import connection
    
    table_name = 'inspections_compliancequota'
    
    with connection.cursor() as cursor:
        if connection.vendor == 'mysql':
            cursor.execute("""
                SELECT COUNT(*) 
                FROM information_schema.STATISTICS 
                WHERE TABLE_SCHEMA = DATABASE() 
                AND TABLE_NAME = %s 
                AND INDEX_NAME = %s
            """, [table_name, index_name])
        else:
            cursor.execute("""
                SELECT COUNT(*) 
                FROM information_schema.STATISTICS 
                WHERE TABLE_NAME = %s 
                AND INDEX_NAME = %s
            """, [table_name, index_name])
        
        index_exists = cursor.fetchone()[0] > 0
        
        if not index_exists:
            fields_str = ', '.join(fields)
            cursor.execute(f"CREATE INDEX {index_name} ON {table_name} ({fields_str})")


def add_indexes_forward(apps, schema_editor):
    """Add new indexes if they don't exist"""
    safe_add_index(apps, schema_editor, 'inspections_law_a15f50_idx', ['law', 'year', 'month'])
    safe_add_index(apps, schema_editor, 'inspections_year_ffa421_idx', ['year', 'month'])


def remove_indexes_reverse(apps, schema_editor):
    """Remove indexes if they exist"""
    from django.db import connection
    table_name = 'inspections_compliancequota'
    
    indexes_to_remove = ['inspections_law_a15f50_idx', 'inspections_year_ffa421_idx']
    
    with connection.cursor() as cursor:
        for index_name in indexes_to_remove:
            if connection.vendor == 'mysql':
                cursor.execute("""
                    SELECT COUNT(*) 
                    FROM information_schema.STATISTICS 
                    WHERE TABLE_SCHEMA = DATABASE() 
                    AND TABLE_NAME = %s 
                    AND INDEX_NAME = %s
                """, [table_name, index_name])
            else:
                cursor.execute("""
                    SELECT COUNT(*) 
                    FROM information_schema.STATISTICS 
                    WHERE TABLE_NAME = %s 
                    AND INDEX_NAME = %s
                """, [table_name, index_name])
            
            index_exists = cursor.fetchone()[0] > 0
            
            if index_exists:
                cursor.execute(f"ALTER TABLE {table_name} DROP INDEX {index_name}")


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0011_alter_compliancequota_unique_together_and_more'),
    ]

    operations = [
        # Safely remove old index if it exists
        migrations.RunPython(safe_remove_index, migrations.RunPython.noop),
        # Safely add new indexes if they don't exist
        migrations.RunPython(add_indexes_forward, remove_indexes_reverse),
    ]
