# Generated by Django 4.2.24 on 2025-10-04 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0002_populate_normalized_data'),
        ('inspections', '0012_alter_inspection_section_chief_decision_and_more'),
    ]

    operations = [
    ]
