# Generated by Django 4.2.24 on 2025-10-04 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0013_merge_20251004_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspectiondecision',
            name='action',
        ),
        migrations.RemoveField(
            model_name='inspectiondecision',
            name='compliance_status',
        ),
        migrations.RemoveField(
            model_name='inspectiondecision',
            name='inspection',
        ),
        migrations.RemoveField(
            model_name='inspectiondecision',
            name='performed_by',
        ),
        migrations.DeleteModel(
            name='Law',
        ),
        migrations.AlterUniqueTogether(
            name='workflowrule',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='workflowrule',
            name='action',
        ),
        migrations.RemoveField(
            model_name='workflowrule',
            name='next_status',
        ),
        migrations.RemoveField(
            model_name='workflowrule',
            name='status',
        ),
        migrations.DeleteModel(
            name='ComplianceStatus',
        ),
        migrations.DeleteModel(
            name='InspectionDecision',
        ),
        migrations.DeleteModel(
            name='InspectionStatus',
        ),
        migrations.DeleteModel(
            name='WorkflowAction',
        ),
        migrations.DeleteModel(
            name='WorkflowRule',
        ),
    ]
