// Establishment-related constants

// Allowed provinces (Ilocos Region)
export const ALLOWED_PROVINCES = [
  "LA UNION",
  "ILOCOS SUR", 
  "ILOCOS NORTE",
  "PANGASINAN",
];

// Predefined Nature of Business options
export const NATURE_OF_BUSINESS_OPTIONS = [
  "RESTAURANT/FOOD SERVICE",
  "RETAIL/WHOLESALE",
  "MANUFACTURING",
  "CONSTRUCTION",
  "TRANSPORTATION",
  "HEALTHCARE/MEDICAL",
  "EDUCATION/TRAINING",
  "HOSPITALITY/TOURISM",
  "AGRICULTURE/FARMING",
  "FISHING/AQUACULTURE",
  "MINING",
  "ENERGY/POWER",
  "TELECOMMUNICATIONS",
  "BANKING/FINANCE",
  "INSURANCE",
  "REAL ESTATE",
  "CONSULTING SERVICES",
  "LEGAL SERVICES",
  "ACCOUNTING SERVICES",
  "MARKETING/ADVERTISING",
  "INFORMATION TECHNOLOGY",
  "RESEARCH & DEVELOPMENT",
  "WASTE MANAGEMENT",
  "WATER SUPPLY",
  "GOVERNMENT SERVICES",
  "NON-PROFIT/CHARITY",
  "ENTERTAINMENT/RECREATION",
  "SPORTS/FITNESS",
  "BEAUTY/COSMETICS",
  "AUTOMOTIVE SERVICES",
  "REPAIR SERVICES",
  "CLEANING SERVICES",
  "SECURITY SERVICES",
  "OTHERS"
];

// Ilocos Region coordinates for auto-zoom
export const ILOCOS_REGION_BOUNDS = {
  north: 18.6,
  south: 15.4,
  east: 121.2,
  west: 119.2
};

// Ilocos Region center coordinates
export const ILOCOS_REGION_CENTER = {
  latitude: 16.5,
  longitude: 120.2
};

// Comprehensive mapping of provinces to their cities/municipalities in Ilocos Region
export const ILOCOS_CITIES_BY_PROVINCE = {
  "LA UNION": [
    "SAN FERNANDO",
    "AGOO",
    "ARINGAY",
    "BACNOTAN",
    "BAGULIN",
    "BALAOAN",
    "BANGAR",
    "BAUANG",
    "BURGOS",
    "CABA",
    "LUNA",
    "NAGUILIAN",
    "PUGO",
    "ROSARIO",
    "SAN GABRIEL",
    "SAN JUAN",
    "SANTO TOMAS",
    "SANTOL",
    "SUDIPEN",
    "TUBAO"
  ],
  "ILOCOS SUR": [
    "VIGAN",
    "CANDON",
    "ALILEM",
    "BANAYOYO",
    "BANTAY",
    "BURGOS",
    "CABUGAO",
    "CAOAYAN",
    "CERVANTES",
    "GALIMUYOD",
    "GREGORIO DEL PILAR",
    "LIDLIDDA",
    "MAGSINGAL",
    "NAGBUKEL",
    "NARVACAN",
    "QUIRINO",
    "SALCEDO",
    "SAN EMILIO",
    "SAN ESTEBAN",
    "SAN ILDEFONSO",
    "SAN JUAN",
    "SAN VICENTE",
    "SANTA",
    "SANTA CATALINA",
    "SANTA CRUZ",
    "SANTA LUCIA",
    "SANTA MARIA",
    "SANTIAGO",
    "SANTO DOMINGO",
    "SIGAY",
    "SINAIT",
    "SUGPON",
    "SUYO",
    "TAGUDIN"
  ],
  "ILOCOS NORTE": [
    "LAOAG",
    "BATAC",
    "ADAMS",
    "BACARRA",
    "BADOC",
    "BANGUI",
    "BANNA",
    "BURGOS",
    "CARASI",
    "CURRIMAO",
    "DINGRAS",
    "DUMALNEG",
    "MARCOS",
    "NUEVA ERA",
    "PAGUDPUD",
    "PAOAY",
    "PASUQUIN",
    "PIDDIG",
    "PINILI",
    "SAN NICOLAS",
    "SARRAT",
    "SOLSONA",
    "VINTAR"
  ],
  "PANGASINAN": [
    "ALAMINOS",
    "DAGUPAN",
    "SAN CARLOS",
    "URDANETA",
    "AGNO",
    "AGUILAR",
    "ALCALA",
    "ANDA",
    "ASINGAN",
    "BALUNGAO",
    "BANI",
    "BASISTA",
    "BAUTISTA",
    "BAYAMBANG",
    "BINALONAN",
    "BINMALEY",
    "BOLINAO",
    "BUGALLON",
    "BURGOS",
    "CALASIAO",
    "DASOL",
    "INFANTA",
    "LABRADOR",
    "LAOAC",
    "LINGAYEN",
    "MABINI",
    "MALASIQUI",
    "MANAOAG",
    "MANGALDAN",
    "MANGATAREM",
    "MAPANDAN",
    "NATIVIDAD",
    "POZORRUBIO",
    "ROSALES",
    "SAN FABIAN",
    "SAN JACINTO",
    "SAN MANUEL",
    "SAN NICOLAS",
    "SAN QUINTIN",
    "SANTA BARBARA",
    "SANTA MARIA",
    "SANTO TOMAS",
    "SISON",
    "SUAL",
    "TAYUG",
    "UMINGAN",
    "URBIZTONDO",
    "VILLASIS"
  ]
};

// Postal codes for Ilocos Region cities
export const POSTAL_CODES_BY_CITY = {
  "LA UNION": {
    "SAN FERNANDO": "2500",
    "AGOO": "2504",
    "ARINGAY": "2503",
    "BACNOTAN": "2515",
    "BAGULIN": "2512",
    "BALAOAN": "2517",
    "BANGAR": "2519",
    "BAUANG": "2501",
    "BURGOS": "2510",
    "CABA": "2502",
    "LUNA": "2518",
    "NAGUILIAN": "2511",
    "PUGO": "2508",
    "ROSARIO": "2506",
    "SAN GABRIEL": "2513",
    "SAN JUAN": "2514",
    "SANTO TOMAS": "2505",
    "SANTOL": "2516",
    "SUDIPEN": "2509",
    "TUBAO": "2507"
  },
  "ILOCOS SUR": {
    "VIGAN": "2700",
    "CANDON": "2710",
    "ALILEM": "2706",
    "BANAYOYO": "2708",
    "BANTAY": "2727",
    "BURGOS": "2724",
    "CABUGAO": "2732",
    "CAOAYAN": "2731",
    "CERVANTES": "2718",
    "GALIMUYOD": "2709",
    "GREGORIO DEL PILAR": "2720",
    "LIDLIDDA": "2723",
    "MAGSINGAL": "2730",
    "NAGBUKEL": "2725",
    "NARVACAN": "2704",
    "QUIRINO": "2721",
    "SALCEDO": "2711",
    "SAN EMILIO": "2722",
    "SAN ESTEBAN": "2708",
    "SAN ILDEFONSO": "2728",
    "SAN JUAN": "2734",
    "SAN VICENTE": "2726",
    "SANTA": "2703",
    "SANTA CATALINA": "2701",
    "SANTA CRUZ": "2713",
    "SANTA LUCIA": "2712",
    "SANTA MARIA": "2705",
    "SANTIAGO": "2707",
    "SANTO DOMINGO": "2729",
    "SIGAY": "2719",
    "SINAIT": "2733",
    "SUGPON": "2715",
    "SUYO": "2714",
    "TAGUDIN": "2716"
  },
  "ILOCOS NORTE": {
    "LAOAG": "2900",
    "BATAC": "2906",
    "ADAMS": "2922",
    "BACARRA": "2916",
    "BADOC": "2904",
    "BANGUI": "2920",
    "BANNA": "2908",
    "BURGOS": "2918",
    "CARASI": "2911",
    "CURRIMAO": "2912",
    "DINGRAS": "2913",
    "DUMALNEG": "2921",
    "MARCOS": "2907",
    "NUEVA ERA": "2909",
    "PAGUDPUD": "2919",
    "PAOAY": "2902",
    "PASUQUIN": "2917",
    "PIDDIG": "2914",
    "PINILI": "2905",
    "SAN NICOLAS": "2901",
    "SARRAT": "2915",
    "SOLSONA": "2910",
    "VINTAR": "2915"
  },
  "PANGASINAN": {
    "ALAMINOS": "2404",
    "DAGUPAN": "2400",
    "SAN CARLOS": "2420",
    "URDANETA": "2428",
    "AGNO": "2408",
    "AGUILAR": "2415",
    "ALCALA": "2425",
    "ANDA": "2405",
    "ASINGAN": "2439",
    "BALUNGAO": "2442",
    "BANI": "2407",
    "BASISTA": "2422",
    "BAUTISTA": "2424",
    "BAYAMBANG": "2423",
    "BINALONAN": "2436",
    "BINMALEY": "2417",
    "BOLINAO": "2406",
    "BUGALLON": "2416",
    "BURGOS": "2410",
    "CALASIAO": "2418",
    "DASOL": "2411",
    "INFANTA": "2412",
    "LABRADOR": "2402",
    "LAOAC": "2437",
    "LINGAYEN": "2401",
    "MABINI": "2409",
    "MALASIQUI": "2421",
    "MANAOAG": "2430",
    "MANGALDAN": "2432",
    "MANGATAREM": "2413",
    "MAPANDAN": "2427",
    "NATIVIDAD": "2446",
    "POZORRUBIO": "2435",
    "ROSALES": "2441",
    "SAN FABIAN": "2433",
    "SAN JACINTO": "2431",
    "SAN MANUEL": "2438",
    "SAN NICOLAS": "2447",
    "SAN QUINTIN": "2444",
    "SANTA BARBARA": "2419",
    "SANTA MARIA": "2440",
    "SANTO TOMAS": "2426",
    "SISON": "2434",
    "SUAL": "2414",
    "TAYUG": "2445",
    "UMINGAN": "2443",
    "URBIZTONDO": "2414",
    "VILLASIS": "2429"
  }
};

// Sample barangays for each city (2-3 per city for initial implementation)
export const BARANGAYS_BY_CITY = {
  "LA UNION": {
    "SAN FERNANDO": ["Bacsil", "Carlatan", "Poro"],
    "AGOO": ["Capas", "Nazareno", "San Antonio"],
    "ARINGAY": ["Alabang", "Poblacion", "San Juan"],
    "BACNOTAN": ["Balasiao", "Poblacion", "Sagap"],
    "BAGULIN": ["Alibangsay", "Poblacion", "Tagudtud"],
    "BALAOAN": ["Balaoan", "Poblacion", "Ranao"],
    "BANGAR": ["Consuegra", "Poblacion", "Ranao"],
    "BAUANG": ["Poblacion", "Payocpoc", "San Vicente"],
    "BURGOS": ["Poblacion", "San Juan", "Tebag"],
    "CABA": ["Poblacion", "San Carlos", "San Juan"],
    "LUNA": ["Poblacion", "Rizal", "San Nicolas"],
    "NAGUILIAN": ["Poblacion", "Rizal", "San Francisco"],
    "PUGO": ["Poblacion", "Rizal", "San Vicente"],
    "ROSARIO": ["Poblacion", "Rizal", "San Vicente"],
    "SAN GABRIEL": ["Poblacion", "Rizal", "San Nicolas"],
    "SAN JUAN": ["Poblacion", "Rizal", "San Nicolas"],
    "SANTO TOMAS": ["Poblacion", "Rizal", "San Nicolas"],
    "SANTOL": ["Poblacion", "Rizal", "San Vicente"],
    "SUDIPEN": ["Poblacion", "Rizal", "San Vicente"],
    "TUBAO": ["Poblacion", "Rizal", "San Vicente"]
  },
  "ILOCOS SUR": {
    "VIGAN": ["Ayusan Norte", "Ayusan Sur", "Poblacion"],
    "CANDON": ["Bagani", "Poblacion", "San Jose"],
    "ALILEM": ["Alilem Daya", "Poblacion", "San Juan"],
    "BANAYOYO": ["Poblacion", "Rizal", "San Juan"],
    "BANTAY": ["Poblacion", "Rizal", "San Nicolas"],
    "BURGOS": ["Poblacion", "Rizal", "San Vicente"],
    "CABUGAO": ["Poblacion", "Rizal", "San Nicolas"],
    "CAOAYAN": ["Poblacion", "Rizal", "San Vicente"],
    "CERVANTES": ["Poblacion", "Rizal", "San Juan"],
    "GALIMUYOD": ["Poblacion", "Rizal", "San Juan"],
    "GREGORIO DEL PILAR": ["Poblacion", "Rizal", "San Nicolas"],
    "LIDLIDDA": ["Poblacion", "Rizal", "San Juan"],
    "MAGSINGAL": ["Poblacion", "Rizal", "San Vicente"],
    "NAGBUKEL": ["Poblacion", "Rizal", "San Juan"],
    "NARVACAN": ["Poblacion", "Rizal", "San Nicolas"],
    "QUIRINO": ["Poblacion", "Rizal", "San Juan"],
    "SALCEDO": ["Poblacion", "Rizal", "San Vicente"],
    "SAN EMILIO": ["Poblacion", "Rizal", "San Juan"],
    "SAN ESTEBAN": ["Poblacion", "Rizal", "San Nicolas"],
    "SAN ILDEFONSO": ["Poblacion", "Rizal", "San Juan"],
    "SAN JUAN": ["Poblacion", "Rizal", "San Vicente"],
    "SAN VICENTE": ["Poblacion", "Rizal", "San Juan"],
    "SANTA": ["Poblacion", "Rizal", "San Nicolas"],
    "SANTA CATALINA": ["Poblacion", "Rizal", "San Juan"],
    "SANTA CRUZ": ["Poblacion", "Rizal", "San Nicolas"],
    "SANTA LUCIA": ["Poblacion", "Rizal", "San Juan"],
    "SANTA MARIA": ["Poblacion", "Rizal", "San Vicente"],
    "SANTIAGO": ["Poblacion", "Rizal", "San Juan"],
    "SANTO DOMINGO": ["Poblacion", "Rizal", "San Nicolas"],
    "SIGAY": ["Poblacion", "Rizal", "San Juan"],
    "SINAIT": ["Poblacion", "Rizal", "San Nicolas"],
    "SUGPON": ["Poblacion", "Rizal", "San Juan"],
    "SUYO": ["Poblacion", "Rizal", "San Nicolas"],
    "TAGUDIN": ["Poblacion", "Rizal", "San Juan"]
  },
  "ILOCOS NORTE": {
    "LAOAG": ["Brgy. 1", "Brgy. 16", "Brgy. 31"],
    "BATAC": ["Brgy. 1", "Brgy. 10", "Brgy. 20"],
    "ADAMS": ["Adams", "Poblacion", "San Juan"],
    "BACARRA": ["Poblacion", "Rizal", "San Nicolas"],
    "BADOC": ["Poblacion", "Rizal", "San Juan"],
    "BANGUI": ["Poblacion", "Rizal", "San Vicente"],
    "BANNA": ["Poblacion", "Rizal", "San Nicolas"],
    "BURGOS": ["Poblacion", "Rizal", "San Juan"],
    "CARASI": ["Poblacion", "Rizal", "San Vicente"],
    "CURRIMAO": ["Poblacion", "Rizal", "San Nicolas"],
    "DINGRAS": ["Poblacion", "Rizal", "San Juan"],
    "DUMALNEG": ["Poblacion", "Rizal", "San Vicente"],
    "MARCOS": ["Poblacion", "Rizal", "San Nicolas"],
    "NUEVA ERA": ["Poblacion", "Rizal", "San Juan"],
    "PAGUDPUD": ["Poblacion", "Rizal", "San Vicente"],
    "PAOAY": ["Poblacion", "Rizal", "San Nicolas"],
    "PASUQUIN": ["Poblacion", "Rizal", "San Juan"],
    "PIDDIG": ["Poblacion", "Rizal", "San Vicente"],
    "PINILI": ["Poblacion", "Rizal", "San Nicolas"],
    "SAN NICOLAS": ["Poblacion", "Rizal", "San Juan"],
    "SARRAT": ["Poblacion", "Rizal", "San Vicente"],
    "SOLSONA": ["Poblacion", "Rizal", "San Nicolas"],
    "VINTAR": ["Poblacion", "Rizal", "San Juan"]
  },
  "PANGASINAN": {
    "ALAMINOS": ["Poblacion", "Rizal", "San Nicolas"],
    "DAGUPAN": ["Barangay I", "Barangay II", "Barangay III"],
    "SAN CARLOS": ["Poblacion", "Rizal", "San Nicolas"],
    "URDANETA": ["Poblacion", "Rizal", "San Vicente"],
    "AGNO": ["Poblacion", "Rizal", "San Juan"],
    "AGUILAR": ["Poblacion", "Rizal", "San Nicolas"],
    "ALCALA": ["Poblacion", "Rizal", "San Vicente"],
    "ANDA": ["Poblacion", "Rizal", "San Juan"],
    "ASINGAN": ["Poblacion", "Rizal", "San Nicolas"],
    "BALUNGAO": ["Poblacion", "Rizal", "San Juan"],
    "BANI": ["Poblacion", "Rizal", "San Vicente"],
    "BASISTA": ["Poblacion", "Rizal", "San Nicolas"],
    "BAUTISTA": ["Poblacion", "Rizal", "San Juan"],
    "BAYAMBANG": ["Poblacion", "Rizal", "San Vicente"],
    "BINALONAN": ["Poblacion", "Rizal", "San Nicolas"],
    "BINMALEY": ["Poblacion", "Rizal", "San Juan"],
    "BOLINAO": ["Poblacion", "Rizal", "San Vicente"],
    "BUGALLON": ["Poblacion", "Rizal", "San Nicolas"],
    "BURGOS": ["Poblacion", "Rizal", "San Juan"],
    "CALASIAO": ["Poblacion", "Rizal", "San Vicente"],
    "DASOL": ["Poblacion", "Rizal", "San Nicolas"],
    "INFANTA": ["Poblacion", "Rizal", "San Juan"],
    "LABRADOR": ["Poblacion", "Rizal", "San Vicente"],
    "LAOAC": ["Poblacion", "Rizal", "San Nicolas"],
    "LINGAYEN": ["Poblacion", "Rizal", "San Juan"],
    "MABINI": ["Poblacion", "Rizal", "San Vicente"],
    "MALASIQUI": ["Poblacion", "Rizal", "San Nicolas"],
    "MANAOAG": ["Poblacion", "Rizal", "San Juan"],
    "MANGALDAN": ["Poblacion", "Rizal", "San Vicente"],
    "MANGATAREM": ["Poblacion", "Rizal", "San Nicolas"],
    "MAPANDAN": ["Poblacion", "Rizal", "San Juan"],
    "NATIVIDAD": ["Poblacion", "Rizal", "San Vicente"],
    "POZORRUBIO": ["Poblacion", "Rizal", "San Nicolas"],
    "ROSALES": ["Poblacion", "Rizal", "San Juan"],
    "SAN FABIAN": ["Poblacion", "Rizal", "San Vicente"],
    "SAN JACINTO": ["Poblacion", "Rizal", "San Nicolas"],
    "SAN MANUEL": ["Poblacion", "Rizal", "San Juan"],
    "SAN NICOLAS": ["Poblacion", "Rizal", "San Vicente"],
    "SAN QUINTIN": ["Poblacion", "Rizal", "San Nicolas"],
    "SANTA BARBARA": ["Poblacion", "Rizal", "San Juan"],
    "SANTA MARIA": ["Poblacion", "Rizal", "San Vicente"],
    "SANTO TOMAS": ["Poblacion", "Rizal", "San Nicolas"],
    "SISON": ["Poblacion", "Rizal", "San Juan"],
    "SUAL": ["Poblacion", "Rizal", "San Vicente"],
    "TAYUG": ["Poblacion", "Rizal", "San Nicolas"],
    "UMINGAN": ["Poblacion", "Rizal", "San Juan"],
    "URBIZTONDO": ["Poblacion", "Rizal", "San Vicente"],
    "VILLASIS": ["Poblacion", "Rizal", "San Nicolas"]
  }
};