// Establishment-related constants

// Allowed provinces (Ilocos Region)
export const ALLOWED_PROVINCES = [
  "LA UNION",
  "ILOCOS SUR", 
  "ILOCOS NORTE",
  "PANGASINAN",
];

// Predefined Nature of Business options
export const NATURE_OF_BUSINESS_OPTIONS = [
  "RESTAURANT/FOOD SERVICE",
  "RETAIL/WHOLESALE",
  "MANUFACTURING",
  "CONSTRUCTION",
  "TRANSPORTATION",
  "HEALTHCARE/MEDICAL",
  "EDUCATION/TRAINING",
  "HOSPITALITY/TOURISM",
  "AGRICULTURE/FARMING",
  "FISHING/AQUACULTURE",
  "MINING",
  "ENERGY/POWER",
  "TELECOMMUNICATIONS",
  "BANKING/FINANCE",
  "INSURANCE",
  "REAL ESTATE",
  "CONSULTING SERVICES",
  "LEGAL SERVICES",
  "ACCOUNTING SERVICES",
  "MARKETING/ADVERTISING",
  "INFORMATION TECHNOLOGY",
  "RESEARCH & DEVELOPMENT",
  "WASTE MANAGEMENT",
  "WATER SUPPLY",
  "GOVERNMENT SERVICES",
  "NON-PROFIT/CHARITY",
  "ENTERTAINMENT/RECREATION",
  "SPORTS/FITNESS",
  "BEAUTY/COSMETICS",
  "AUTOMOTIVE SERVICES",
  "REPAIR SERVICES",
  "CLEANING SERVICES",
  "SECURITY SERVICES",
  "OTHERS"
];

// Ilocos Region coordinates for auto-zoom
export const ILOCOS_REGION_BOUNDS = {
  north: 18.6,
  south: 15.4,
  east: 121.2,
  west: 119.2
};

// Ilocos Region center coordinates
export const ILOCOS_REGION_CENTER = {
  latitude: 16.5,
  longitude: 120.2
};

// Comprehensive mapping of provinces to their cities/municipalities in Ilocos Region
export const ILOCOS_CITIES_BY_PROVINCE = {
  "LA UNION": [
    "SAN FERNANDO",
    "AGOO",
    "ARINGAY",
    "BACNOTAN",
    "BAGULIN",
    "BALAOAN",
    "BANGAR",
    "BAUANG",
    "BURGOS",
    "CABA",
    "LUNA",
    "NAGUILIAN",
    "PUGO",
    "ROSARIO",
    "SAN GABRIEL",
    "SAN JUAN",
    "SANTO TOMAS",
    "SANTOL",
    "SUDIPEN",
    "TUBAO"
  ],
  "ILOCOS SUR": [
    "VIGAN",
    "CANDON",
    "ALILEM",
    "BANAYOYO",
    "BANTAY",
    "BURGOS",
    "CABUGAO",
    "CAOAYAN",
    "CERVANTES",
    "GALIMUYOD",
    "GREGORIO DEL PILAR",
    "LIDLIDDA",
    "MAGSINGAL",
    "NAGBUKEL",
    "NARVACAN",
    "QUIRINO",
    "SALCEDO",
    "SAN EMILIO",
    "SAN ESTEBAN",
    "SAN ILDEFONSO",
    "SAN JUAN",
    "SAN VICENTE",
    "SANTA",
    "SANTA CATALINA",
    "SANTA CRUZ",
    "SANTA LUCIA",
    "SANTA MARIA",
    "SANTIAGO",
    "SANTO DOMINGO",
    "SIGAY",
    "SINAIT",
    "SUGPON",
    "SUYO",
    "TAGUDIN"
  ],
  "ILOCOS NORTE": [
    "LAOAG",
    "BATAC",
    "ADAMS",
    "BACARRA",
    "BADOC",
    "BANGUI",
    "BANNA",
    "BURGOS",
    "CARASI",
    "CURRIMAO",
    "DINGRAS",
    "DUMALNEG",
    "MARCOS",
    "NUEVA ERA",
    "PAGUDPUD",
    "PAOAY",
    "PASUQUIN",
    "PIDDIG",
    "PINILI",
    "SAN NICOLAS",
    "SARRAT",
    "SOLSONA",
    "VINTAR"
  ],
  "PANGASINAN": [
    "ALAMINOS",
    "DAGUPAN",
    "SAN CARLOS",
    "URDANETA",
    "AGNO",
    "AGUILAR",
    "ALCALA",
    "ANDA",
    "ASINGAN",
    "BALUNGAO",
    "BANI",
    "BASISTA",
    "BAUTISTA",
    "BAYAMBANG",
    "BINALONAN",
    "BINMALEY",
    "BOLINAO",
    "BUGALLON",
    "BURGOS",
    "CALASIAO",
    "DASOL",
    "INFANTA",
    "LABRADOR",
    "LAOAC",
    "LINGAYEN",
    "MABINI",
    "MALASIQUI",
    "MANAOAG",
    "MANGALDAN",
    "MANGATAREM",
    "MAPANDAN",
    "NATIVIDAD",
    "POZORRUBIO",
    "ROSALES",
    "SAN FABIAN",
    "SAN JACINTO",
    "SAN MANUEL",
    "SAN NICOLAS",
    "SAN QUINTIN",
    "SANTA BARBARA",
    "SANTA MARIA",
    "SANTO TOMAS",
    "SISON",
    "SUAL",
    "TAYUG",
    "UMINGAN",
    "URBIZTONDO",
    "VILLASIS"
  ]
};

// Postal codes for Ilocos Region cities
export const POSTAL_CODES_BY_CITY = {
  "LA UNION": {
    "SAN FERNANDO": "2500",
    "AGOO": "2504",
    "ARINGAY": "2503",
    "BACNOTAN": "2515",
    "BAGULIN": "2512",
    "BALAOAN": "2517",
    "BANGAR": "2519",
    "BAUANG": "2501",
    "BURGOS": "2510",
    "CABA": "2502",
    "LUNA": "2518",
    "NAGUILIAN": "2511",
    "PUGO": "2508",
    "ROSARIO": "2506",
    "SAN GABRIEL": "2513",
    "SAN JUAN": "2514",
    "SANTO TOMAS": "2505",
    "SANTOL": "2516",
    "SUDIPEN": "2509",
    "TUBAO": "2507"
  },
  "ILOCOS SUR": {
    "VIGAN": "2700",
    "CANDON": "2710",
    "ALILEM": "2706",
    "BANAYOYO": "2708",
    "BANTAY": "2727",
    "BURGOS": "2724",
    "CABUGAO": "2732",
    "CAOAYAN": "2731",
    "CERVANTES": "2718",
    "GALIMUYOD": "2709",
    "GREGORIO DEL PILAR": "2720",
    "LIDLIDDA": "2723",
    "MAGSINGAL": "2730",
    "NAGBUKEL": "2725",
    "NARVACAN": "2704",
    "QUIRINO": "2721",
    "SALCEDO": "2711",
    "SAN EMILIO": "2722",
    "SAN ESTEBAN": "2708",
    "SAN ILDEFONSO": "2728",
    "SAN JUAN": "2734",
    "SAN VICENTE": "2726",
    "SANTA": "2703",
    "SANTA CATALINA": "2701",
    "SANTA CRUZ": "2713",
    "SANTA LUCIA": "2712",
    "SANTA MARIA": "2705",
    "SANTIAGO": "2707",
    "SANTO DOMINGO": "2729",
    "SIGAY": "2719",
    "SINAIT": "2733",
    "SUGPON": "2715",
    "SUYO": "2714",
    "TAGUDIN": "2716"
  },
  "ILOCOS NORTE": {
    "LAOAG": "2900",
    "BATAC": "2906",
    "ADAMS": "2922",
    "BACARRA": "2916",
    "BADOC": "2904",
    "BANGUI": "2920",
    "BANNA": "2908",
    "BURGOS": "2918",
    "CARASI": "2911",
    "CURRIMAO": "2912",
    "DINGRAS": "2913",
    "DUMALNEG": "2921",
    "MARCOS": "2907",
    "NUEVA ERA": "2909",
    "PAGUDPUD": "2919",
    "PAOAY": "2902",
    "PASUQUIN": "2917",
    "PIDDIG": "2914",
    "PINILI": "2905",
    "SAN NICOLAS": "2901",
    "SARRAT": "2915",
    "SOLSONA": "2910",
    "VINTAR": "2915"
  },
  "PANGASINAN": {
    "ALAMINOS": "2404",
    "DAGUPAN": "2400",
    "SAN CARLOS": "2420",
    "URDANETA": "2428",
    "AGNO": "2408",
    "AGUILAR": "2415",
    "ALCALA": "2425",
    "ANDA": "2405",
    "ASINGAN": "2439",
    "BALUNGAO": "2442",
    "BANI": "2407",
    "BASISTA": "2422",
    "BAUTISTA": "2424",
    "BAYAMBANG": "2423",
    "BINALONAN": "2436",
    "BINMALEY": "2417",
    "BOLINAO": "2406",
    "BUGALLON": "2416",
    "BURGOS": "2410",
    "CALASIAO": "2418",
    "DASOL": "2411",
    "INFANTA": "2412",
    "LABRADOR": "2402",
    "LAOAC": "2437",
    "LINGAYEN": "2401",
    "MABINI": "2409",
    "MALASIQUI": "2421",
    "MANAOAG": "2430",
    "MANGALDAN": "2432",
    "MANGATAREM": "2413",
    "MAPANDAN": "2427",
    "NATIVIDAD": "2446",
    "POZORRUBIO": "2435",
    "ROSALES": "2441",
    "SAN FABIAN": "2433",
    "SAN JACINTO": "2431",
    "SAN MANUEL": "2438",
    "SAN NICOLAS": "2447",
    "SAN QUINTIN": "2444",
    "SANTA BARBARA": "2419",
    "SANTA MARIA": "2440",
    "SANTO TOMAS": "2426",
    "SISON": "2434",
    "SUAL": "2414",
    "TAYUG": "2445",
    "UMINGAN": "2443",
    "URBIZTONDO": "2414",
    "VILLASIS": "2429"
  }
};

// Sample barangays for each city (2-3 per city for initial implementation)
export const BARANGAYS_BY_CITY = {
  "LA UNION": {
    "San Fernando": [ "Abut", "Apaleng", "Bacsil", "Bangbangolan", "Bangcusay", "Barangay I", "Barangay II", "Barangay III", "Barangay IV", "Baraoas", 
    "Bato", "Biday", "Birunget", "Bungro", "Cabaroan", "Cabarsican", "Cadaclan", "Calabugao", "Camansi", "Canaoay", "Carlatan", "Catbangen", 
    "Dallangayan Este", "Dallangayan Oeste", "Dalumpinas Este", "Dalumpinas Oeste", "Ilocanos Norte", "Ilocanos Sur", "Langcuas", "Lingsat", "Madayegdeg", 
    "Mameltac", "Masicong", "Nagyubuyuban", "Namtutan", "Narra Este", "Narra Oeste", "Pacpaco", "Pagdalagan", "Pagdaraoan", "Pagudpud", 
    "Pao Norte", "Pao Sur", "Parian", "Pias", "Poro", "Puspus", "Sacyud", "Sagayad", "San Agustin", "San Francisco", "San Vicente", "Santiago Norte", 
    "Santiago Sur", "Saoay", "Sevilla", "Siboan-Otong", "Tanqui", "Tanquigan" ],
    "AGOO": ["Capas", "Nazareno", "San Antonio"],
    "Aringay": [ "Alaska", "Basca", "Dulao", "Gallano", "Macabato", "Manga", "Pangao-aoan East", "Pangao-aoan West", "Poblacion", "Samara", "San Antonio", "San Benito Norte", 
    "San Benito Sur", "San Eugenio", "San Juan East", "San Juan West", "San Simon East", "San Simon West", "Santa Cecilia", 
    "Santa Lucia", "Santa Rita East", "Santa Rita West", "Santo Rosario East", "Santo Rosario West" ],
    "Bacnotan": [ "Agtipal", "Arosip", "Bacqui", "Bacsil", "Bagutot", "Ballogo", "Baroro", "Bitalag", "Bulala", "Burayoc", "Bussaoit", "Cabaroan", "Cabarsican", "Cabugao", 
    "Calautit", "Carcarmay", "Casiaman", "Galongen", "Guinabang", "Legleg", "Lisqueb", "Mabanengbeng 1st", "Mabanengbeng 2nd", "Maragayap", "Nagatiran", 
    "Nagsaraboan", "Nagsimbaanan", "Nangalisan", "Narra", "Ortega", "Oya-oy", "Paagan", "Pandan", "Pang-pang", "Poblacion", "Quirino", "Raois", "Salincob",
    "San Martin", "Santa Cruz", "Santa Rita", "Sapilang", "Sayoan", "Sipulo", "Tammocalao", "Ubbog", "Zaragosa" ],
    "Bagulin": [ "Alibangsay", "Baay", "Cambaly", "Cardiz", "Dagup", "Libbo", "Suyo", "Tagudtud", "Tio-angan", "Wallayan" ],
    "Balaoan": [ "Almieda", "Antonino", "Apatut", "Ar-arampang", "Baracbac Este", "Baracbac Oeste", "Bet-ang", "Bulbulala", "Bungol", "Butubut Este", 
    "Butubut Norte", "Butubut Oeste", "Butubut Sur", "Cabuaan Oeste", "Calliat", "Calungbuyan", "Camiling", "Dr. Camilo Osias Poblacion", "Guinaburan", 
    "Masupe", "Nagsabaran Norte", "Nagsabaran Sur", "Nalasin", "Napaset", "Pa-o", "Pagbennecan", "Pagleddegan", "Pantar Norte", "Pantar Sur", "Paraoir",
    "Patpata", "Sablut", "San Pablo", "Sinapangan Norte", "Sinapangan Sur", "Tallipugo" ],
    "Bangar": [ "Agdeppa", "Alzate", "Bangaoilan East", "Bangaoilan West", "Barraca", "Cadapli", "Caggao", "Central East No. 1", "Central East No. 2",
    "Central West No. 1", "Central West No. 2", "Central West No. 3", "Consuegra", "General Prim East", "General Prim West", "General Terrero", "Luzong Norte",
    "Luzong Sur", "Maria Cristina East", "Maria Cristina West", "Mindoro", "Nagsabaran", "Paratong No. 3", "Paratong No. 4", "Paratong Norte", "Quintarong",
    "Reyna Regente", "Rissing", "San Blas", "San Cristobal", "Sinapangan Norte", "Sinapangan Sur", "Ubbog" ],
    "Bauang": [ "Acao", "Baccuit Norte", "Baccuit Sur", "Bagbag", "Ballay", "Bawanta", "Boy-utan", "Bucayab", "Cabalayangan", "Cabisilan", 
    "Calumbaya", "Carmay", "Casilagan", "Central East", "Central West", "Dili", "Disso-or", "Guerrero", "Lower San Agustin", "Nagrebcan", 
    "Pagdalagan Sur", "Palintucang", "Palugsi-Limmansangan", "Parian Este", "Parian Oeste", "Paringao", "Payocpoc Norte Este", "Payocpoc Norte Oeste",
    "Payocpoc Sur", "Pilar", "Pottot", "Pudoc", "Pugo", "Quinavite", "Santa Monica", "Santiago", "Taberna", "Upper San Agustin", "Urayong" ],
    "Burgos": [ "Agpay", "Bilis", "Caoayan", "Dalacdac", "Delles", "Imelda", "Libtong", "Linuan", 
    "Lower Tumapoc", "New Poblacion", "Old Poblacion", "Upper Tumapoc" ],
    "Caba": [ "Bautista", "Gana", "Juan Cartas", "Las-ud", "Liquicia", "Poblacion Norte", "Poblacion Sur", "San Carlos", "San Cornelio",
    "San Fermin", "San Gregorio", "San Jose", "Santiago Norte", "Santiago Sur", "Sobredillo", "Urayong", "Wenceslao" ],
    "Luna": [ "Alcala", "Ayaoan", "Barangobong", "Barrientos", "Bungro", "Buselbusel", "Cabalitocan", "Cantoria No. 1", "Cantoria No. 2", 
    "Cantoria No. 3", "Cantoria No. 4", "Carisquis", "Darigayos", "Magallanes", "Magsiping", "Mamay", "Nagrebcan", "Nalvo Norte", "Nalvo Sur", 
    "Napaset", "Oaqui No. 1", "Oaqui No. 2", "Oaqui No. 3", "Oaqui No. 4", "Pila", "Pitpitac", "Rimos No. 1", "Rimos No. 2", "Rimos No. 3", 
    "Rimos No. 4", "Rimos No. 5", "Rissing", "Salcedo", "Santo Domingo Norte", "Santo Domingo Sur", "Sucoc Norte", "Sucoc Sur", "Suyo", "Tallaoen", "Victoria" ],
    "Naguilian": [ "Aguioas", "Al-alinao Norte", "Al-alinao Sur", "Ambaracao Norte", "Ambaracao Sur", "Angin", "Balecbec", "Bancagan",
    "Baraoas Norte", "Baraoas Sur", "Bariquir", "Bato", "Bimmotobot", "Cabaritan Norte", "Cabaritan Sur", "Casilagan", "Dal-lipaoen", 
    "Daramuangan", "Guesset", "Gusing Norte", "Gusing Sur", "Imelda", "Lioac Norte", "Lioac Sur", "Magungunay", "Mamat-ing Norte", "Mamat-ing Sur",
    "Nagsidorisan", "Natividad", "Ortiz", "Ribsuan", "San Antonio", "San Isidro", "Sili", "Suguidan Norte", "Suguidan Sur", "Tuddingan" ],
    "Pugo": [ "Ambalite", "Ambangonan", "Cares", "Cuenca", "Duplas", "Maoasoas Norte", "Maoasoas Sur", "Palina", "Poblacion East",
    "Poblacion West", "San Luis", "Saytan", "Tavora East", "Tavora Proper" ],
    "Rosario": [ "Alipang", "Ambangonan", "Amlang", "Bacani", "Bangar", "Bani", "Benteng-Sapilang", "Cadumanian", "Camp One", "Carunuan East", 
    "Carunuan West", "Casilagan", "Cataguingtingan", "Concepcion", "Damortis", "Gumot-Nagcolaran", "Inabaan Norte", "Inabaan Sur", "Marcos",
    "Nagtagaan", "Nangcamotian", "Parasapas", "Poblacion East", "Poblacion West", "Puzon", "Rabon", "San Jose", "Subusub", "Tabtabungao", "Tanglag", "Tay-ac", "Udiao", "Vila" ],
    "San Gabriel": [ "Amontoc", "Apayao", "Balbalayang", "Bayabas", "Bucao", "Bumbuneg", "Daking", "Lacong", "Lipay Este", "Lipay Norte",
    "Lipay Proper", "Lipay Sur", "Lon-oy", "Poblacion", "Polipol" ],
    "San Juan": [ "Allangigan", "Aludaid", "Bacsayan", "Balballosa", "Bambanay", "Bugbugcao", "Caarusipan", "Cabaroan", 
    "Cabugnayan", "Cacapian", "Caculangan", "Calincamasan", "Casilagan", "Catdongan", "Dangdangla", "Dasay", "Dinanum", "Duplas", 
    "Guinguinabang", "Ili Norte", "Ili Sur", "Legleg", "Lubing", "Nadsaag", "Nagsabaran", "Naguirangan", "Naguituban", "Nagyubuyuban", "Oaquing", 
    "Pacpacac", "Pagdildilan", "Panicsican", "Quidem", "San Felipe", "Santa Rosa", "Santo Rosario", "Saracat", "Sinapangan", "Taboc", "Talogtog", "Urbiztondo" ],
    "Santo Tomas": [ "Ambitacay", "Bail", "Balaoc", "Balsaan", "Baybay", "Cabaruan", "Casantaan", "Casilagan", "Cupang", "Damortis", 
    "Fernando", "Linong", "Lomboy", "Malabago", "Namboongan", "Namonitan", "Narvacan", "Patac", "Poblacion", "Pongpong", "Raois", "Tococ", "Tubod", "Ubagan" ],
    "Santol": [ "Corrooy", "Lettac Norte", "Lettac Sur", "Mangaan", "Paagan", "Poblacion", "Puguil", "Ramot", "Sapdaan", "Sasaba", "Tubaday" ],
    "Sudipen": [ "Bigbiga", "Bulalaan", "Castro", "Duplas", "Ilocano", "Ipet", "Maliclico", "Namaltugan", "Old Central", "Poblacion",
    "Porporiket", "San Francisco Norte", "San Francisco Sur", "San Jose", "Sengngat", "Turod", "Up-uplas" ],
    "Tubao": [ "Amallapay", "Anduyan", "Caoigue", "Francia Sur", "Francia West", "Garcia", "Gonzales", "Halog East", "Halog West", "Leones East",
    "Leones West", "Linapew", "Lloren", "Magsaysay", "Pideg", "Poblacion", "Rizal", "Santa Teresa" ]
  },
  "ILOCOS_SUR": {
  "ALILEM": [
    "Alilem Daya",
    "Amilongan",
    "Anaao",
    "Apang",
    "Apaya",
    "Batbato",
    "Daddaay",
    "Dalawa",
    "Kiat"
  ],
  "BANAYOYO": [
    "Bagbagotot",
    "Banbanaal",
    "Bisangol",
    "Cadanglaan",
    "Casilagan Norte",
    "Casilagan Sur",
    "Elefante",
    "Guardia",
    "Lintic",
    "Lopez",
    "Montero",
    "Naguimba",
    "Pila",
    "Poblacion"
  ],
  "BANTAY": [
    "Aggay",
    "An-annam",
    "Balaleng",
    "Banaoang",
    "Barangay 1",
    "Barangay 2",
    "Barangay 3",
    "Barangay 4",
    "Barangay 5",
    "Barangay 6",
    "Bulag",
    "Buquig",
    "Cabalanggan",
    "Cabaroan",
    "Cabusligan",
    "Capangdanan",
    "Guimod",
    "Lingsat",
    "Malingeb",
    "Mira",
    "Naguiddayan",
    "Ora",
    "Paing",
    "Puspus",
    "Quimmarayan",
    "Sagneb",
    "Sagpat",
    "San Isidro",
    "San Julian",
    "San Mariano",
    "Sinabaan",
    "Taguiporo",
    "Taleb",
    "Tay-ac"
  ],
  "BURGOS": [
    "Ambugat",
    "Balugang",
    "Bangbangar",
    "Bessang",
    "Cabcaburao",
    "Cadacad",
    "Callitong",
    "Dayanki",
    "Dirdirig",
    "Lesseb",
    "Lubing",
    "Lucaban",
    "Luna",
    "Macaoayan",
    "Mambug",
    "Manaboc",
    "Mapanit",
    "Nagpanaoan",
    "Paduros",
    "Patac",
    "Poblacion Norte",
    "Poblacion Sur",
    "Sabangan Pinggan",
    "Subadi Norte",
    "Subadi Sur",
    "Taliao"
  ],
  "CABUGAO": [
    "Alinaay",
    "Aragan",
    "Arnap",
    "Baclig",
    "Bato",
    "Bonifacio",
    "Bungro",
    "Cacadiran",
    "Caellayan",
    "Carusipan",
    "Catucdaan",
    "Cuancabal",
    "Cuantacla",
    "Daclapan",
    "Dardarat",
    "Lipit",
    "Maradodon",
    "Margaay",
    "Nagsantaan",
    "Nagsincaoan",
    "Namruangan",
    "Pila",
    "Pug-os",
    "Quezon",
    "Reppaac",
    "Rizal",
    "Sabang",
    "Sagayaden",
    "Salapasap",
    "Salomague",
    "Sisim",
    "Turod",
    "Turod-Patac"
  ],
  "CANDON": [
    "Allangigan Primero",
    "Allangigan Segundo",
    "Amguid",
    "Ayudante",
    "Bagani Camposanto",
    "Bagani Gabor",
    "Bagani Tocgo",
    "Bagani Ubbog",
    "Bagar",
    "Balingaoan",
    "Bugnay",
    "Calaoaan",
    "Calongbuyan",
    "Caterman",
    "Cubcubboot",
    "Darapidap",
    "Langlangca Primero",
    "Langlangca Segundo",
    "Oaig-Daya",
    "Palacapac",
    "Paras",
    "Parioc Primero",
    "Parioc Segundo",
    "Patpata Primero",
    "Patpata Segundo",
    "Paypayad",
    "Salvador Primero",
    "Salvador Segundo",
    "San Agustin",
    "San Andres",
    "San Antonio",
    "San Isidro",
    "San Jose",
    "San Juan",
    "San Nicolas",
    "San Pedro",
    "Santo Tomas",
    "Tablac",
    "Talogtog",
    "Tamurong Primero",
    "Tamurong Segundo",
    "Villarica"
   ],
   "CERVANTES": [
    "Aluling",
    "Comillas Norte",
    "Comillas South",
    "Concepcion",
    "Dinwede East",
    "Dinwede West",
    "Lusong",
    "Remedios",
    "San Juan",
    "Tablac",
    "Tuddingan"
  ],
  "GALIMUYOD": [
    "Abaya",
    "Bagani Campo",
    "Balugnos",
    "Banbanaal",
    "Baracbac",
    "Barbar",
    "Betwagan",
    "Bitong",
    "Burayoc",
    "Cabaritan",
    "Cal-laoan",
    "Calongbuyan",
    "Daldagan",
    "Legaspi",
    "Lira",
    "Mambug",
    "Mataragan",
    "Napo",
    "Poblacion",
    "Sacaang"
  ],
  "LIDLIDDA": [
    "Baay",
    "Banucal",
    "Bequi-Walin",
    "Bugui",
    "Cabusligan",
    "Carcarabasa",
    "Labut",
    "Poblacion",
    "San Vicente",
    "Suysuyan"
  ],
  "MAGSINGAL": [
    "Al-aludig",
    "Bato",
    "Bungro",
    "Cabaritan",
    "Cabulalaan",
    "Cacandongan",
    "Capariaan",
    "Dilatong",
    "Lacong",
    "Mabileg",
    "Maluno Norte",
    "Maluno Sur",
    "Nagbacalan",
    "Poblacion Norte",
    "Poblacion Sur",
    "San Basilio",
    "San Julian",
    "San Ramon",
    "San Roque",
    "San Vicente",
    "Saoang",
    "Sived",
    "Subec",
    "Turod"
  ],
  "NAGBUKEL": [
    "Cadacad",
    "Camaoan",
    "Daday",
    "Lablabinag",
    "Mabileg",
    "Poblacion East",
    "Poblacion West",
    "Quibal",
    "Rang-ay",
    "Sengngat",
    "Turod"
  ],
  "NARVACAN": [
    "Ambulogan",
    "Bacsil",
    "Banaoang",
    "Banual",
    "Barangobong",
    "Buliclic",
    "Cabaroan",
    "Cadacad",
    "Camarao",
    "Camanggaan",
    "Camarao",
    "Canaan",
    "Darapidap",
    "Dinalaoan",
    "Estancia",
    "Isic-isic",
    "Lubing",
    "Napu",
    "Orence",
    "Poblacion Norte",
    "Poblacion Sur",
    "Puzon",
    "Quinarayan",
    "Rang-ay",
    "San Antonio",
    "San Jose",
    "San Pedro",
    "Santa Cecilia",
    "Sapang",
    "Sulvec",
    "Tacling",
    "Tamurong First",
    "Tamurong Second",
    "Turod"
  ],
  "QUIRINO": [
    "Banoen",
    "Banoen Norte",
    "Bulag",
    "Cabaritan",
    "Cabaruyan",
    "Cabcaburao",
    "Lang-ayan",
    "Legleg",
    "Malideg",
    "Namitpit",
    "Poblacion",
    "Santo Tomas"
  ],
  "SALCEDO": [
    "Banbanaal",
    "Bazar",
    "Calangcuasan",
    "Calle",
    "Candon Norte",
    "Candon Sur",
    "Capangpangan",
    "Casanay",
    "Dinaratan",
    "Labnig",
    "Mambug",
    "Nagsabaran Norte",
    "Nagsabaran Sur",
    "Poblacion Norte",
    "Poblacion Sur",
    "Quibit-quibit",
    "Tiblong",
    "Vintar"
  ],
  "SAN EMILIO": [
    "Cabaroan",
    "Cabaritan",
    "Danac",
    "Kisikis",
    "Mabugbug",
    "Matibuey",
    "Poblacion",
    "Sibsibbu",
    "Tiagan"
  ],
  "SAN ESTEBAN": [
    "Aparri",
    "Baclig",
    "Bungro",
    "Cabittaogan",
    "Daniw",
    "Dinanum",
    "Lalong",
    "Oribi",
    "Poblacion Norte",
    "Poblacion Sur",
    "San Pablo",
    "San Rafael",
    "San Sebastian",
    "Santa Cruz",
    "Villa Quirino"
  ],
  "SAN ILDEFONSO": [
    "Arnap",
    "Bacsil",
    "Bubuos",
    "Calongbuyan",
    "Gabao",
    "Poblacion Norte",
    "Poblacion Sur",
    "San Miguel",
    "Sayoan"
  ],
  "SAN JUAN": [
    "Abaccan",
    "Ammubuan",
    "Barbarangay",
    "Batbato",
    "Bitalag",
    "Cabaritan",
    "Camarao",
    "Camangaan",
    "Labut",
    "Libtong",
    "Madarang",
    "Nagsabaran Norte",
    "Nagsabaran Sur",
    "Poblacion Norte",
    "Poblacion Sur",
    "Sabangan Pinggan",
    "Sangtad",
    "Subec",
    "Turod"
  ],
  "SAN VICENTE": [
    "Bantaoay",
    "Bayubay Norte",
    "Bayubay Sur",
    "Lubong",
    "Poblacion",
    "San Sebastian",
    "Santa Rosa",
    "Tay-ac"
  ],
  "SANTA": [
    "Aguing",
    "Banaoang",
    "Calongbuyan",
    "Camposanto",
    "Guinabang",
    "Magsaysay",
    "Nalasin",
    "Oribi",
    "Puspus",
    "Poblacion Norte",
    "Poblacion Sur",
    "San Agustin",
    "San Francisco",
    "San Nicolas",
    "Santa Maria"
  ],
  "SANTA CATALINA": [
    "Cabittaogan",
    "Cabaroan",
    "Cabusligan",
    "Camposanto",
    "Mangaan",
    "Poblacion Norte",
    "Poblacion Sur",
    "San Sebastian",
    "Santa Rosa"
  ],
  "SANTA CRUZ": [
    "Ambucao",
    "Babayoan",
    "Bayugao Este",
    "Bayugao Oeste",
    "Buliclic",
    "Callusa",
    "Camanggaan",
    "Capatac-an",
    "Labut Norte",
    "Labut Sur",
    "Luba",
    "Nagtupacan",
    "Poblacion Norte",
    "Poblacion Sur",
    "Pudoc",
    "Quirino",
    "Sabangan Pinggan",
    "San Sebastian",
    "Santo Tomas",
    "Tapat",
    "Turod"
  ],
  "SANTA LUCIA": [
    "Alinaya",
    "Bacong",
    "Bagani Campo",
    "Bagoen",
    "Banbanaba",
    "Barangay 1 Poblacion",
    "Barangay 2 Poblacion",
    "Barangay 3 Poblacion",
    "Barangay 4 Poblacion",
    "Barangay 5 Poblacion",
    "Barangay 6 Poblacion",
    "Barangay 7 Poblacion",
    "Barangay 8 Poblacion",
    "Barangay 9 Poblacion",
    "Barangay 10 Poblacion",
    "Barangay 11 Poblacion",
    "Barangay 12 Poblacion",
    "Barangay 13 Poblacion",
    "Barangay 14 Poblacion",
    "Barangay 15 Poblacion",
    "Barangay 16 Poblacion",
    "Barangay 17 Poblacion",
    "Barangay 18 Poblacion",
    "Barangay 19 Poblacion",
    "Barangay 20 Poblacion",
    "Barangay 21 Poblacion"
  ],
  "SANTA MARIA": [
    "Aguing",
    "Bacnit",
    "Bagbagotot",
    "Barangay Uno",
    "Barangay Dos",
    "Barangay Tres",
    "Barangay Quatro",
    "Barangay Cinco",
    "Barangay Seis",
    "Barangay Siete",
    "Barangay Ocho",
    "Barangay Nueve",
    "Barangay Diez",
    "Barangay Once",
    "Barangay Dose",
    "Barangay Trese",
    "Barangay Katorse",
    "Barangay Kinse",
    "Barangay Diesisais"
  ],
  "SANTIAGO": [
    "Ambucao",
    "Ayusan Norte",
    "Ayusan Sur",
    "Baclig",
    "Bantay",
    "Binongan",
    "Cabaritan",
    "Camanggaan",
    "Daddaay",
    "Lubong",
    "Magsaysay",
    "Namruangan",
    "Nagpanaoan",
    "Orence",
    "Poblacion Norte",
    "Poblacion Sur",
    "Sabangan Pinggan",
    "San Antonio",
    "San Ramon",
    "Santa Barbara",
    "Santa Rosa",
    "Santo Tomas"
  ],
  "SANTO DOMINGO": [
    "Barangay 1 Poblacion",
    "Barangay 2 Poblacion",
    "Barangay 3 Poblacion",
    "Barangay 4 Poblacion",
    "Barangay 5 Poblacion",
    "Barangay 6 Poblacion",
    "Barangay 7 Poblacion",
    "Barangay 8 Poblacion",
    "Barangay 9 Poblacion",
    "Barangay 10 Poblacion",
    "Barangay 11 Poblacion",
    "Barangay 12 Poblacion",
    "Barangay 13 Poblacion",
    "Barangay 14 Poblacion",
    "Barangay 15 Poblacion",
    "Barangay 16 Poblacion",
    "Barangay 17 Poblacion",
    "Barangay 18 Poblacion",
    "Barangay 19 Poblacion",
    "Barangay 20 Poblacion"
  ]
,
  "SINAIT": [
    "Baliw",
    "Barbar",
    "Baliw",
    "Bateria",
    "Binacud",
    "Cabaritan",
    "Calanutian",
    "Casilagan",
    "Dadalaquiten Norte",
    "Dadalaquiten Sur",
    "Dinalaoan",
    "Lubong",
    "Nagcullooban",
    "Nagongburan",
    "Poblacion",
    "Parparoroc",
    "Rang-ay",
    "Rivas",
    "Sabangan Pinggan",
    "San Agustin",
    "San Francisco",
    "San Isidro",
    "San Jose",
    "San Nicolas",
    "San Pedro",
    "San Ramon",
    "San Roque",
    "Santa Cruz",
    "Santa Maria",
    "Santo Tomas",
    "Suso",
    "Turod"
  ],
  "SUGPON": [
    "Aluling",
    "Balbalayang",
    "Bucao",
    "Legleg",
    "Licungan",
    "Poblacion Norte",
    "Poblacion Sur",
    "Suagayan"
  ],
  "SUYO": [
    "Baringcucurong",
    "Uso",
    "Barangay Uno",
    "Barangay Dos",
    "Barangay Tres",
    "Barangay Quatro",
    "Barangay Cinco",
    "Barangay Seis",
    "Barangay Siete",
    "Barangay Ocho",
    "Barangay Nueve",
    "Barangay Diez"
  ],
  "TAGUDIN": [
    "Ag-Aguman",
    "Alcala",
    "Ambalayat",
    "Bacani",
    "Badio",
    "Bimmanga",
    "Bio",
    "Borono",
    "Cabigbigaan",
    "Cabulanglangan",
    "Caburao",
    "Dardarat",
    "Del Pilar",
    "Lantag",
    "Luba",
    "Lussoc",
    "Magsaysay",
    "Poblacion",
    "San Felipe",
    "San Miguel",
    "San Ramon",
    "San Vicente",
    "Santa Cruz",
    "Santo Tomas",
    "Turod"
  ] 
},
  "ILOCOS_NORTE": {
  "ADAMS": ["Adams"],
  "BACARRA": [
    "Bani","Buyon","Cabaruan","Cabulalaan","Cabusligan","Cadaratan","Calioet-Libong",
    "Casilian","Corocor","Duripes","Ganagan","Libtong","Macupit","Nambaran","Natba",
    "Paninaan","Pasiocan","Pasngal","Pipias","Pulangi","Pungto","San Agustin I",
    "San Agustin II","San Andres I","San Andres II","San Gabriel I","San Gabriel II",
    "San Pedro I","San Pedro II","San Roque I","San Roque II","San Simon I","San Simon II",
    "San Vicente","Sangil","Santa Filomena I","Santa Filomena II","Santa Rita",
    "Santo Cristo I","Santo Cristo II","Tambidao","Teppang","Tubburan"
  ],
  "BADOC": [
    "Alay-Nangbabaan","Alogoog","Ar-arusip","Aring","Balbaldez","Bato","Camanga",
    "Canaan","Caraitan","Gabut Norte","Gabut Sur","Garreta","La Virgen Milagrosa",
    "Labut","Lacuben","Lubigan","Mabusag Norte","Mabusag Sur","Madupayas","Morong",
    "Nagrebcan","Napu","Pagsanahan Norte","Pagsanahan Sur","Paltit","Parang","Pasuc",
    "Santa Cruz Norte","Santa Cruz Sur","Saud","Turod"
  ],
  "BANGUI": [
    "Abaca","Bacsil","Banban","Baruyen","Dadaor","Lanao","Malasin","Manayon",
    "Masikil","Nagbalagan","Payac","San Lorenzo","Taguiporo","Utol"
  ],
  "BANNA": [
    "Balioeg","Bangsar","Barbarangay","Binacag","Bomitog","Bugasi","Caestebanan",
    "Caribquib","Catagtaguen","Crispina","Hilario","Imelda","Lorenzo","Macayepyep",
    "Marcos","Nagpatayan","Sinamar","Tabtabagan","Valdez","Valenciano"
  ],
  "BATAC": [
    "Ablan Poblacion","Acosta Poblacion","Aglipay","Baay","Baligat","Baoa East","Baoa West",
    "Barani","Ben-agan","Bil-loca","Biningan","Bungon","Callaguip","Camandingan",
    "Camguidan","Cangrunaan","Capacuan","Caunayan","Colo","Dariwdiw","Lacub","Mabaleng",
    "Magnuang","Maipalig","Nagbacalan","Naguirangan","Palongpong","Palpalicong","Parangopong",
    "Payao","Pimentel","Quiling Norte","Quiling Sur","Quiom","Rayuray","Ricarte Poblacion",
    "San Julian","San Mateo","San Pedro","Suabit","Sumader","Tabug","Valdez Poblacion"
  ],
  "BURGOS": [
    "Ablan Sarat","Agaga","Bayog","Bobon","Buduan","Nagsurot","Paayas","Pagali","Poblacion",
    "Saoit","Tanap"
  ],
  "CARASI": ["Angset","Barbaqueso","Virbira"],
  "CURRIMAO": [
    "Anggapang Norte","Anggapang Sur","Bimmanga","Cabuusan","Comcomloong","Gaang",
    "Lang-ayan-Baramban","Lioes","Maglaoi Centro","Maglaoi Norte","Maglaoi Sur",
    "Paguludan-Salindeg","Pangil","Pias Norte","Pias Sur","Poblacion I","Poblacion II",
    "Salugan","San Simeon","Santa Cruz","Tapao-Tigue","Torre","Victoria"
  ],
  "DINGRAS": [
    "Albano","Bacsil","Bagut","Baresbes","Barong","Bungcag","Cali","Capasan","Dancel",
    "Elizabeth","Espiritu","Foz","Guerrero","Lanas","Lumbad","Madamba","Mandaloque",
    "Medina","Parado","Peralta","Puruganan","Root","Sagpatan","Saludares","San Esteban",
    "San Francisco","San Marcelino","San Marcos","Sulquiano","Suyo","Ver"
  ],
  "DUMALNEG": ["Cabaritan","Kalaw","Quibel","San Isidro"],
  "LAOAG": [
    "Barangay No. 1, San Lorenzo","Barangay No. 2, Santa Joaquina","Barangay No. 3, Nuestra Señora del Rosario",
    "Barangay No. 4, San Guillermo","Barangay No. 5, San Pedro","Barangay No. 6, San Agustin",
    "Barangay No. 7-A, Nuestra Señora de Natividad","Barangay No. 7-B, Nuestra Señora de Natividad",
    "Barangay No. 8, San Vicente","Barangay No. 9, Santa Angela","Barangay No. 10, San Jose",
    "Barangay No. 11, Santa Balbina","Barangay No. 12, San Isidro","Barangay No. 13, Nuestra Señora de Visitacion",
    "Barangay No. 14, Santo Tomas","Barangay No. 15, San Guillermo","Barangay No. 16, San Jacinto",
    "Barangay No. 17, San Francisco","Barangay No. 18, San Quirino","Barangay No. 19, Santa Marcela",
    "Barangay No. 20, San Miguel","Barangay No. 21, San Pedro","Barangay No. 22, San Andres",
    "Barangay No. 23, San Matias","Barangay No. 24, Nuestra Señora de Consolacion","Barangay No. 25, Santa Cayetana",
    "Barangay No. 26, San Marcelino","Barangay No. 27, Nuestra Señora de Soledad","Barangay No. 28, San Bernardo",
    "Barangay No. 29, Santo Tomas","Barangay No. 30-A, Suyo","Barangay No. 30-B, Santa Maria",
    "Barangay No. 31, Talingaan","Barangay No. 32-A, La Paz East","Barangay No. 32-B, La Paz West",
    "Barangay No. 32-C, La Paz East","Barangay No. 33-A, La Paz Proper","Barangay No. 33-B, La Paz Proper",
    "Barangay No. 34-A, Gabu Norte West","Barangay No. 34-B, Gabu Norte East","Barangay No. 35, Gabu Sur",
    "Barangay No. 36, Araniw","Barangay No. 37, Calayab","Barangay No. 38-A, Mangato East",
    "Barangay No. 38-B, Mangato West","Barangay No. 39, Santa Rosa","Barangay No. 40, Balatong",
    "Barangay No. 41, Balacad","Barangay No. 42, Apaya","Barangay No. 43, Cavit","Barangay No. 44, Zamboanga",
    "Barangay No. 45, Tangid","Barangay No. 46, Nalbo","Barangay No. 47, Bengcag",
    "Barangay No. 48-A, Cabungaan North","Barangay No. 48-B, Cabungaan South",
    "Barangay No. 49-A, Darayday","Barangay No. 49-B, Raraburan","Barangay No. 50, Buttong",
    "Barangay No. 51-A, Nangalisan East","Barangay No. 51-B, Nangalisan West","Barangay No. 52-A, San Mateo",
    "Barangay No. 52-B, Lataag","Barangay No. 53, Rioeng","Barangay No. 54-A, Lagui-Sail",
    "Barangay No. 54-B, Camangaan","Barangay No. 55-A, Barit-Pandan","Barangay No. 55-B, Salet-Bulangon",
    "Barangay No. 55-C, Vira","Barangay No. 56-A, Bacsil North","Barangay No. 56-B, Bacsil South",
    "Barangay No. 57, Pila","Barangay No. 58, Casili","Barangay No. 59-A, Dibua South",
    "Barangay No. 59-B, Dibua North","Barangay No. 60-A, Caaoacan","Barangay No. 60-B, Madiladig",
    "Barangay No. 61, Cataban","Barangay No. 62-A, Navotas North","Barangay No. 62-B, Navotas South"
  ],
  "MARCOS": [
    "Cacafean","Daquioag","Elizabeth","Escoda","Ferdinand","Fortuna","Imelda","Lydia",
    "Mabuti","Pacifico","Santiago","Tabucbuc","Valdez"
  ],
  "NUEVA ERA": [
    "Acnam","Barangobong","Barikir","Bugayong","Cabittauran","Caray","Garnaden",
    "Naguillan","Poblacion","Santo Niño","Uguis"
  ],
  "PAGUDPUD": [
    "Aggasi","Baduang","Balaoi","Burayoc","Caparispisan","Caunayan","Dampig","Ligaya",
    "Pancian","Pasaleng","Poblacion 1","Poblacion 2","Saguigui","Saud","Subec","Tarrag"
  ],
  "PAOAY": [
    "Bacsil","Cabagoan","Cabangaran","Callaguip","Cayubog","Dolores","Laoa","Masintoc",
    "Monte","Mumulaan","Nagbacalan","Nalasin","Nanguyudan","Oaig-Upay-Abulao","Pambaran",
    "Pannaratan","Paratong","Pasil","Salbang","San Agustin","San Blas","San Juan",
    "San Pedro","San Roque","Sangladan Poblacion","Santa Rita","Sideg","Suba","Sungadan",
    "Surgui","Veronica"
  ],
  "PASUQUIN": [
    "Batuli","Binsang","Caruan","Carusikis","Carusipan","Dadaeman","Darupidip","Davila",
    "Dilanis","Dilavo","Estancia","Naglicuan","Nagsanga","Nalvo","Ngabangab","Pangil",
    "Poblacion 1","Poblacion 2","Poblacion 3","Poblacion 4","Pragata","Puyupuyan","Salpad",
    "San Juan","Santa Catalina","Santa Matilde","Sapat","Sulbec","Sulongan","Surong",
    "Susugaen","Tabungao","Tadao"
  ],
  "PIDDIG": [
    "Ab-abut","Abucay","Anao","Arua-ay","Bimmanga","Boyboy","Cabaroan","Calambeg",
    "Callusa","Dupitac","Estancia","Gayamat","Lagandit","Libnaoan","Loing","Maab-abaca",
    "Mangitayag","Maruaya","San Antonio","Santa Maria","Sucsuquen","Tangaoan","Tonoton"
  ],
  "PINILI": [
    "Aglipay","Apatut-Lubong","Badio","Barbar","Buanga","Bulbulala","Bungro","Cabaroan",
    "Capangdanan","Dalayap","Darat","Gulpeng","Liliputen","Lumbaan-Bicbica","Nagtrigoan",
    "Pagdilao","Pugaoan","Puritac","Puzol","Sacritan","Salanap","Santo Tomas","Tartarabang",
    "Upon","Valbuena"
  ],
  "SAN NICOLAS": [
    "San Agustin","San Baltazar","San Bartolome","San Cayetano","San Eugenio","San Fernando",
    "San Francisco","San Gregorio","San Guillermo","San Ildefonso","San Jose","San Juan Bautista",
    "San Lorenzo","San Lucas","San Marcos","San Miguel","San Pablo","San Paulo","San Pedro",
    "San Rufino","San Silvestre","Santa Asuncion","Santa Cecilia","Santa Monica"
  ],
  "SARRAT": [
    "San Agustin","San Andres","San Antonio","San Bernabe","San Cristobal","San Felipe",
    "San Francisco","San Isidro","San Joaquin","San Jose","San Juan","San Leandro",
    "San Lorenzo","San Manuel","San Marcos","San Nicolas","San Pedro","San Roque",
    "San Vicente","Santa Barbara","Santa Magdalena","Santa Rosa","Santo Santiago","Santo Tomas"
  ],
  "SOLSONA": [
    "Aguitap","Bagbag","Bagbago","Barcelona","Bubuos","Capurictan","Catangraran","Darasdas",
    "Juan","Laureta","Lipay","Maananteng","Manalpac","Mariquet","Nagpatpatan","Nalasin",
    "Puttao","San Juan","San Julian","Santa Ana","Santiago","Talugtog"
  ],
  "VINTAR": [
    "Abkir","Alejo Malasig","Alsem","Bago","Bulbulala","Cabangaran","Cabayo","Cabisocolan",
    "Canaam","Columbia","Dagupan","Dipilat","Esperanza","Ester","Isic Isic","Lubnac",
    "Mabanbanag","Malampa","Manarang","Margaay","Namoroc","Parparoroc","Parut",
    "Pedro F. Alviar","Salsalamagui","San Jose","San Nicolas","San Pedro","San Ramon",
    "San Roque","Santa Maria","Tamdagan","Visaya"
  ]
},
  "PANGASINAN": {
"AGNO": [
    "Aloleng", "Bangan-Oda", "Boboy", "Gayusan", "Magsaysay", "Poblacion East",
    "Poblacion West", "Raniag", "San Juan", "Tupa"
],
"AGUILAR": [
    "Bayaoas", "Bocboc", "Buer", "Laoag", "Manlocboc", "Poblacion",
    "Pogomboa", "San Jose", "Tampac", "Tolongues"
],
"ALAMINOS CITY": [
    "Amandiego", "Balangobong", "Balayang", "Bisocol", "Bued", "Cabatuan",
    "Cayucay", "Dulacac", "Inerangan", "Landoc", "Linmansangan", "Lucap",
    "Magsaysay", "Mona", "Palamis", "Pandan", "Poblacion", "Pocal-Pocal",
    "Sabangan", "San Antonio", "San Jose", "San Roque", "San Vicente",
    "Santa Maria", "Tanaytay", "Tawin-Tawin", "Telbang"
],
"ANDA": [
    "Awag", "Batiarao", "Cabalitian", "Carot", "Dolaoan", "Imbo", "Macaleeng",
    "Mal-ong", "Malacapas", "Namagbagan", "Patar", "Poblacion", "Roxas",
    "Sablig", "San Jose", "Santa Rita", "Siapar", "Tanaytay", "Toritori", "Tondol"
],
"ASINGAN": [
    "Ariston Este", "Ariston Weste", "Bantog", "Baro", "Bobonan", "Carosucan Norte",
    "Carosucan Sur", "Cawayan", "Domanpot", "Dupac", "Macalong", "Palaris",
    "Poblacion East", "Poblacion West", "Sanchez", "San Vicente Este", "San Vicente Weste",
    "Sobol", "Toboy"
],
"BALUNGAO": [
    "Anambongan", "Angayan Norte", "Angayan Sur", "Capulaan", "Esmeralda",
    "Kita-Kita", "Legaspi", "Mabini", "Poblacion", "Poponto", "San Andres",
    "San Aurelio 1st", "San Aurelio 2nd", "San Aurelio 3rd", "San Joaquin",
    "San Julian", "San Leon", "San Raymundo", "San Vicente", "Tomas"
],
"BANI": [
    "Ambabaay", "Aporao", "Ballag", "Banog Norte", "Banog Sur", "Colayo",
    "Dacap Norte", "Dacap Sur", "Darawey", "Garrita", "Luac", "Macabit",
    "Masidem", "Poblacion", "Quinaoayanan", "Ranao", "San Jose", "San Miguel",
    "San Simon", "Tiep", "Tipor", "Tugui Grande", "Tugui Norte"
],
"BASISTA": [
    "Alilao", "Cabeldatan", "Dumpay", "Malimpec East", "Malimpec West",
    "Navatat", "Obong", "Osmeña", "Patacbo", "Poblacion East", "Poblacion West",
    "Primicias", "San Juan", "Santo Domingo", "Santo Niño"
],
"BAUTISTA": [
    "Artacho", "Bani", "Bayambang", "Binalay", "Cabuaan", "Cabalitian",
    "Caipang", "Caloocan Norte", "Caloocan Sur", "Nandacan", "Pangpang",
    "Poblacion East", "Poblacion West", "Poponto", "Primicias", "San Pedro",
    "Santo Domingo", "Tebag"
],
"BUGALLON": [
    "Anagao", "Angarian", "Bacayao", "Balayo", "Bolaoen", "Buenlag",
    "Cabaruan", "Caanamongan", "Coliling", "Domalandan", "Gueguesangen",
    "Hacienda", "Laguit Padilla", "Lambayan", "Laoag", "Lepang", "Lincod",
    "Poblacion", "Polong", "Portic", "Salasa", "Salomague Norte", "Salomague Sur",
    "San Isidro Norte", "San Isidro Sur", "San Jose", "San Pablo", "Santa Maria",
    "Taloy", "Tolongues", "Tubigan"
],
"BURGOS": [
    "Anapao", "Cacayasen", "Catuday", "Concordia", "Don Matias", "Ilio-Ilio",
    "Papallasen", "Poblacion", "San Miguel", "San Pascual", "Tambac"
],
"DAGUPAN CITY": [
    "Bacayao Norte", "Bacayao Sur", "Barangay II", "Barangay IV", "Bolosan",
    "Bonuan Binloc", "Bonuan Boquig", "Bonuan Gueset", "Calmay", "Carael",
    "Caranglaan", "Herrero", "Lasip Chico", "Lasip Grande", "Lomboy",
    "Lucao", "Malued", "Mamalingling", "Mangin", "Mayombo", "Pantal",
    "Poblacion Oeste", "Pogo Chico", "Pogo Grande", "Pugaro Suit", "Salapingao",
    "Tambac", "Tapuac", "Tebeng"
],
"DASOL": [
    "Alilao", "Amahit", "Boboy", "Eguia", "Gais-Guipe", "Gomez", "Macalang",
    "Malimpin", "Magsaysay", "Osmeña", "Poblacion East", "Poblacion West",
    "San Vicente", "Tambac", "Tanobon", "Tara"
],
"ESPANOLA": [
    "Alibago", "Bantayan", "Cabrera", "Cahampan", "Cayungnan", "Culong",
    "Macayucay", "Magsaysay", "Malacapas", "Nandacan", "Poblacion", "San Antonio"
], 
"LABRADOR": [
    "Bolo", "Burgos", "Cabayaoasan", "Camangaan", "Colayo", "Dulacac", "Laois",
    "Magsaysay", "Poblacion", "San Gonzalo", "San Jose", "San Rafael", "Suaco"
],
"LAOAC": [
    "Ano", "Ariston Este", "Ariston Weste", "Bantog", "Baro", "Cabalitian",
    "Calmay", "Casantaan", "Domalandan", "Lepa", "Macalong", "Poblacion East",
    "Poblacion West", "San Juan", "San Pedro", "Talogtog"
],
"LINGAYEN": [
    "Aliwekwek", "Baay", "Bantayan", "Capandanan", "Domalandan Center",
    "Domalandan East", "Domalandan West", "Libsong East", "Libsong West",
    "Malawa", "Maniboc", "Naguelguel", "Namolan", "Pangapisan North",
    "Pangapisan Sur", "Poblacion", "Quibaol", "Rosario", "Sabangan", "Talogtog",
    "Tonton", "Tumbar"
],
"MABINI": [
    "Agdao", "Bacnono", "Barlo", "Calzada", "Caabiangaan", "Cabanaetan",
    "Dulacac", "Laois", "Magsaysay", "Namagbagan", "Patar", "Poblacion",
    "San Juan", "San Pedro", "Tagudin", "Villanueva"
],
"MALASIQUI": [
    "Amacalan", "Anando", "Apaya", "Bakitiw", "Balite Sur", "Balaoang", "Banaoang",
    "Baritao", "Cabaritan", "Calbueg", "Doyong", "Inlambo", "Lareg-Lareg",
    "Lomboy", "Lunec", "Mabini", "Malimpuec", "Palospos", "Poblacion",
    "Polong Norte", "Polong Sur", "Taloy", "Tobuan"
],
"MANAOAG": [
    "Anolid", "Baliw", "Bantog", "Bued", "Calaocan Dilan", "Calaocan Norte",
    "Calaocan Sur", "Caloocan Centro", "Guiguilonen", "Licsi", "Luna", "Oraan East",
    "Oraan West", "Poblacion", "San Ramon", "Sapang", "Tayug"
],
"MANGALDAN": [
    "Anolid", "Banaoang", "Bolosan", "Embarcadero", "Gueset", "Gueguesangen",
    "Macayug", "Manat", "Nibaliw", "Poblacion", "Salay", "Talogtog", "Umando"
],
"MANGATAREM": [
    "Amagbagan", "Amansabina", "Anolid", "Banog Norte", "Banog Sur", "Bocboc",
    "Buenlag", "Cabayaoasan", "Casibong", "Dorongan", "Gueset", "Lawak", "Licsi",
    "Magsaysay", "Poblacion", "Potiocan", "Tobuan", "Umanday"
],
"MAPANDAN": [
    "Aserda", "Bana", "Banaoang", "Coral", "Golden", "Jimenez", "Lambao",
    "Laois", "Poblacion", "Talogtog", "Tayug"
],
"MARIAHONG": [
    "Bacnar", "Bacong", "Balangobong", "Calepaan", "Domalandan", "Lomboy",
    "Malimpuec", "Manga", "Poblacion", "San Antonio", "Taloy", "Umando"
],
"NATIVIDAD": [
    "Aguitap", "Alang", "Bacnar", "Balangobong", "Batchelor East", "Batchelor West",
    "Carmay East", "Carmay West", "Casilaan", "Matolong", "Poblacion", "San Eugenio",
    "San Macario Norte", "San Macario Sur", "Sapinit", "Santo Tomas", "Tolongues"
],
"POZORRUBIO": [
    "Alipangpang", "Amagbagan", "Bantog", "Batchelor East", "Batchelor West",
    "Bobonan", "Cabatling", "Carmay East", "Carmay West", "Doyong", "Imbalbalatong",
    "Malingeb", "Palacpalac", "Poblacion", "Rosario", "Sugcong", "Talogtog"
],
"ROSALES": [
    "Acop", "Bacnar", "Carmay East", "Carmay West", "Don Antonio Village", "Palakipak",
    "Poblacion", "Pogomboa", "Salavante", "San Antonio", "San Pedro", "San Vicente",
    "Tayug", "Tomling"
],
"SAN CARLOS CITY": [
    "Abanon", "Agdao", "Amanusa", "Bacnar", "Balite Sur", "Bani", "Bocboc",
    "Cabarsican", "Cabayaoasan", "Calepaan", "Doyong", "Ilang", "Magsaysay",
    "Palospos", "Poblacion", "Pogomboa", "Taloy", "Tayug"
],
"SAN FABIAN": [
    "Alacan", "Ambalangan Dalin", "Angio", "Balayang", "Baybay Norte", "Baybay Sur",
    "Bigbiga", "Binday", "Bolaoen", "Cabaritan", "Carmay East", "Carmay West",
    "Coliling", "Inmalog", "Lipit-Tomeeng", "Longos", "Palapad", "Poblacion", "Rabong"
],
"SAN JACINTO": [
    "Alacan", "Bagong Pag-asa", "Baybay", "Bolaoen", "Capandanan", "Casilaan",
    "Doyong", "Lareg-Lareg", "Lomboy", "Magsaysay", "Palospos", "Poblacion",
    "San Eugenio", "Taloy", "Tebag"
],
"SAN MANUEL": [
    "Alacan", "Amagbagan", "Bocboc", "Calepaan", "Casantaan", "Gueset", "Laois",
    "Licsi", "Malimpuec", "Palospos", "Poblacion", "San Bonifacio", "Sapang",
    "Talogtog", "Tebeng"
],
"SAN NICOLAS": [
    "Ariston Norte", "Ariston Sur", "Bacnar", "Balangobong", "Calepaan", "Domalandan",
    "Lareg-Lareg", "Malimpuec", "Poblacion East", "Poblacion West", "San Jose",
    "Sobol", "Talogtog"
],
"SAN QUINTIN": [
    "Alipangpang", "Amacalan", "Balangobong", "Baritao", "Cabayaoasan", "Casantaan",
    "Colayo", "Domalandan", "Lareg-Lareg", "Poblacion", "San Pedro", "Sobol"
],
"SISON": [
    "Agdao", "Amagbagan", "Ariston Norte", "Ariston Sur", "Bacnar", "Bantog",
    "Bobonan", "Doyong", "Inmalog", "Labney", "Magsaysay", "Palospos", "Poblacion",
    "Sapang", "Talogtog"
],
"TAYUG": [
    "Amamperez", "Bacnar", "Barangobong", "Carriedo", "Legaspi", "Lepa", "Lomboy",
    "Magallanes", "Poblacion", "San Bartolome", "San Jose", "San Nicolas", "Toketec",
    "Trenchera"
],
"UMINGAN": [
    "Amamperez", "Amaronan", "Bacnar", "Baritao", "Calepaan", "Casantaan", "Concepcion",
    "Domalandan", "Flores", "Lareg-Lareg", "Malimpec East", "Malimpec West",
    "Poblacion East", "Poblacion West", "San Pedro", "Sobol", "Talogtog", "Tayug"
],
"URBIZTONDO": [
    "Aguedo", "Bacayao", "Bangar", "Baug", "Baybay", "Cabayaoasan", "Camagsingalan",
    "Dulag", "Gueset", "La Paz", "Lareg-Lareg", "Magsaysay", "Malibong", "Poblacion",
    "San Francisco", "San Pedro", "Talogtog"
],
"URDANETA CITY": [
    "Anonas", "Bacayao", "Bued", "Cabayaoasan", "Camagsingalan", "Casantaan",
    "Catablan", "Doyong", "Macalong", "Magsaysay", "Nancayasan", "Nancamaliran East",
    "Nancamaliran West", "Nancayasan", "Palina East", "Palina West", "Poblacion",
    "San Vicente", "Santa Lucia", "Santo Domingo"
],
"VILLASIS": [
    "Amamperez", "Barraca", "Cabanbanan", "Cabaritan", "Caramutan", "Labney",
    "Lareg-Lareg", "Lomboy", "Malimpec East", "Malimpec West", "Palospos", "Poblacion",
    "San Blas", "San Bonifacio", "San Pedro", "Tobuan"
]
}
};