# Generated by Django 4.2.17 on 2025-11-13 15:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('middle_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('userlevel', models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Legal Unit', 'Legal Unit'), ('Division Chief', 'Division Chief'), ('Section Chief', 'Section Chief'), ('Unit Head', 'Unit Head'), ('Monitoring Personnel', 'Monitoring Personnel')], max_length=50)),
                ('section', models.CharField(blank=True, choices=[('RA-6969', 'RA-6969'), ('RA-8749', 'RA-8749'), ('RA-9275', 'RA-9275'), ('RA-9003', 'RA-9003'), ('PD-1586', 'PD-1586'), ('PD-1586,RA-8749,RA-9275', 'EIA, Air & Water (Combined)')], max_length=50, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_first_login', models.BooleanField(default=True)),
                ('must_change_password', models.BooleanField(default=False)),
                ('failed_login_attempts', models.PositiveIntegerField(default=0)),
                ('last_failed_login', models.DateTimeField(blank=True, null=True)),
                ('account_locked_until', models.DateTimeField(blank=True, null=True)),
                ('is_account_locked', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'indexes': [models.Index(fields=['first_name', 'last_name'], name='users_user_first_n_6d862e_idx'), models.Index(fields=['email'], name='users_user_email_6f2530_idx'), models.Index(fields=['userlevel'], name='users_user_userlev_a37783_idx')],
            },
        ),
    ]
