# Generated by Django 5.2.5 on 2025-09-11 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='section',
            field=models.CharField(blank=True, choices=[('PD-1586', 'PD-1586'), ('RA-6969', 'RA-6969'), ('RA-8749', 'RA-8749'), ('RA-9275', 'RA-9275'), ('RA-9003', 'RA-9003')], max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='userlevel',
            field=models.CharField(blank=True, choices=[('Legal Unit', 'Legal Unit'), ('Division Chief', 'Division Chief'), ('Section Chief', 'Section Chief'), ('Unit Head', 'Unit Head'), ('Monitoring Personnel', 'Monitoring Personnel')], max_length=50),
        ),
    ]
