# Generated by Django 4.2.17 on 2025-11-15 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=255)),
                ('subject', models.CharField(max_length=500)),
                ('template_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email_type', models.CharField(choices=[('welcome', 'Welcome Email'), ('activation', 'Account Activation'), ('deactivation', 'Account Deactivation'), ('password_reset', 'Password Reset'), ('security_alert', 'Security Alert'), ('other', 'Other')], default='other', max_length=50)),
                ('context_data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queued_emails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='users_email_status_fa6d8c_idx'), models.Index(fields=['recipient_email'], name='users_email_recipie_90b7a5_idx'), models.Index(fields=['email_type'], name='users_email_email_t_17293d_idx')],
            },
        ),
    ]
