# Generated by Django 5.2.5 on 2025-09-11 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_middle_name_user_section_user_userlevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userlevel',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Legal Unit', 'Legal Unit'), ('Division Chief', 'Division Chief'), ('Section Chief', 'Section Chief'), ('Unit Head', 'Unit Head'), ('Monitoring Personnel', 'Monitoring Personnel')], max_length=50),
        ),
    ]
