# Generated by Django 4.2.17 on 2025-11-15 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_emailqueue'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailQueue',
        ),
    ]
