# Generated by Django 4.2.17 on 2025-11-03 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='district',
        ),
    ]
