# Generated by Django 5.2.5 on 2025-09-12 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_userlevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='section',
            field=models.CharField(choices=[('PD-1586', 'PD-1586'), ('RA-6969', 'RA-6969'), ('RA-8749', 'RA-8749'), ('RA-9275', 'RA-9275'), ('RA-9003', 'RA-9003')], max_length=50, null=True),
        ),
    ]
