# Generated by Django 5.2.5 on 2025-09-13 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_user', 'New User Registration'), ('new_establishment', 'New Establishment Created'), ('password_reset', 'Password Reset Request')], max_length=20),
        ),
    ]
