# Generated by Django 5.2.5 on 2025-09-13 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_notification_notification_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
