# Generated by Django 5.2.5 on 2025-09-24 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_is_online_user_last_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_online',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_activity',
        ),
    ]
