# Generated by Django 4.2.24 on 2025-09-29 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='district',
            field=models.CharField(blank=True, choices=[('1st District', '1st District'), ('2nd District', '2nd District'), ('3rd District', '3rd District')], max_length=100, null=True),
        ),
    ]
