# Generated by Django 4.2.24 on 2025-10-02 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_user_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='district',
            field=models.CharField(blank=True, choices=[('La Union - 1st District', 'La Union - 1st District'), ('La Union - 2nd District', 'La Union - 2nd District'), ('La Union - 3rd District', 'La Union - 3rd District'), ('Ilocos Norte - 1st District', 'Ilocos Norte - 1st District'), ('Ilocos Norte - 2nd District', 'Ilocos Norte - 2nd District'), ('Ilocos Sur - 1st District', 'Ilocos Sur - 1st District'), ('Ilocos Sur - 2nd District', 'Ilocos Sur - 2nd District'), ('Pangasinan - 1st District', 'Pangasinan - 1st District'), ('Pangasinan - 2nd District', 'Pangasinan - 2nd District'), ('Pangasinan - 3rd District', 'Pangasinan - 3rd District'), ('Pangasinan - 4th District', 'Pangasinan - 4th District'), ('Pangasinan - 5th District', 'Pangasinan - 5th District'), ('Pangasinan - 6th District', 'Pangasinan - 6th District')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='section',
            field=models.CharField(blank=True, choices=[('RA-6969', 'RA-6969'), ('RA-8749', 'RA-8749'), ('RA-9275', 'RA-9275'), ('RA-9003', 'RA-9003'), ('PD-1586', 'PD-1586'), ('PD-1586,RA-8749,RA-9275', 'EIA, Air & Water (Combined)')], max_length=50, null=True),
        ),
    ]
