# Generated by Django 4.2.24 on 2025-10-04 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_populate_normalized_user_data'),
        ('users', '0015_alter_user_district_alter_user_section'),
    ]

    operations = [
    ]
