# Generated by Django 4.2.24 on 2025-10-04 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_merge_20251004_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='combined_sections',
        ),
        migrations.RemoveField(
            model_name='userassignmenthistory',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='userassignmenthistory',
            name='new_district',
        ),
        migrations.RemoveField(
            model_name='userassignmenthistory',
            name='new_section',
        ),
        migrations.RemoveField(
            model_name='userassignmenthistory',
            name='new_userlevel',
        ),
        migrations.RemoveField(
            model_name='userassignmenthistory',
            name='old_district',
        ),
        migrations.RemoveField(
            model_name='userassignmenthistory',
            name='old_section',
        ),
        migrations.RemoveField(
            model_name='userassignmenthistory',
            name='old_userlevel',
        ),
        migrations.RemoveField(
            model_name='userassignmenthistory',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='userpermission',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userpermission',
            name='granted_by',
        ),
        migrations.RemoveField(
            model_name='userpermission',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_user_userlevel_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_user_section_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_user_district_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_user_is_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_user_level_section_district_idx',
        ),
        migrations.DeleteModel(
            name='District',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
        migrations.DeleteModel(
            name='UserAssignmentHistory',
        ),
        migrations.DeleteModel(
            name='UserLevel',
        ),
        migrations.DeleteModel(
            name='UserPermission',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
