// constants/complianceConstants.js
export const COMPLIANCE_CATEGORIES = {
  DOCUMENTATION: "Documentation",
  CERTIFICATION: "Certification",
  REPORTING: "Reporting",
  PERMITTING: "Permitting",
  OPERATIONAL: "Operational",
  MONITORING: "Monitoring",
  TRAINING: "Training",
};

export const COMPLIANCE_STATUS = {
  COMPLIANT: "Yes",
  NON_COMPLIANT: "No",
};

export const PREDEFINED_REMARKS = [
  "Compliant",        // only appears when Yes
  "Minor Deficiency",
  "Major Deficiency",
  "For Monitoring",
  "Other",
];


export const initialComplianceItems = [
  // PD-1586 (9 rows for ECC conditions)
  {
    lawId: "PD-1586",
    applicableLaw:
      "PD-1586: Environmental Compliance Certificate (ECC) Conditionalities",
    conditionId: "PD-1586-1",
    conditionNumber: "",
    complianceRequirement: "",
    compliant: "N/A",
    remarks: "",
    category: "Documentation",
    priority: "High",
    lawCitation: "",
  },
  {
    lawId: "PD-1586",
    applicableLaw:
      "PD-1586: Environmental Compliance Certificate (ECC) Conditionalities",
    conditionId: "PD-1586-2",
    conditionNumber: "",
    complianceRequirement: "",
    compliant: "N/A",
    remarks: "",
    category: "Documentation",
    priority: "High",
    lawCitation: "",
  },
  {
    lawId: "PD-1586",
    applicableLaw:
      "PD-1586: Environmental Compliance Certificate (ECC) Conditionalities",
    conditionId: "PD-1586-3",
    conditionNumber: "",
    complianceRequirement: "",
    compliant: "N/A",
    remarks: "",
    category: "Documentation",
    priority: "High",
    lawCitation: "",
  },
  {
    lawId: "PD-1586",
    applicableLaw:
      "PD-1586: Environmental Compliance Certificate (ECC) Conditionalities",
    conditionId: "PD-1586-4",
    conditionNumber: "",
    complianceRequirement: "",
    compliant: "N/A",
    remarks: "",
    category: "Documentation",
    priority: "High",
    lawCitation: "",
  },
  {
    lawId: "PD-1586",
    applicableLaw:
      "PD-1586: Environmental Compliance Certificate (ECC) Conditionalities",
    conditionId: "PD-1586-5",
    conditionNumber: "",
    complianceRequirement: "",
    compliant: "N/A",
    remarks: "",
    category: "Documentation",
    priority: "High",
    lawCitation: "",
  },
  {
    lawId: "PD-1586",
    applicableLaw:
      "PD-1586: Environmental Compliance Certificate (ECC) Conditionalities",
    conditionId: "PD-1586-6",
    conditionNumber: "",
    complianceRequirement: "",
    compliant: "N/A",
    remarks: "",
    category: "Documentation",
    priority: "High",
    lawCitation: "",
  },
  {
    lawId: "PD-1586",
    applicableLaw:
      "PD-1586: Environmental Compliance Certificate (ECC) Conditionalities",
    conditionId: "PD-1586-7",
    conditionNumber: "",
    complianceRequirement: "",
    compliant: "N/A",
    remarks: "",
    category: "Documentation",
    priority: "High",
    lawCitation: "",
  },
  {
    lawId: "PD-1586",
    applicableLaw:
      "PD-1586: Environmental Compliance Certificate (ECC) Conditionalities",
    conditionId: "PD-1586-8",
    conditionNumber: "",
    complianceRequirement: "",
    compliant: "N/A",
    remarks: "",
    category: "Documentation",
    priority: "High",
    lawCitation: "",
  },
  {
    lawId: "PD-1586",
    applicableLaw:
      "PD-1586: Environmental Compliance Certificate (ECC) Conditionalities",
    conditionId: "PD-1586-9",
    conditionNumber: "",
    complianceRequirement: "",
    compliant: "N/A",
    remarks: "",
    category: "Documentation",
    priority: "High",
    lawCitation: "",
  },

  {
    lawId: "PD-1586",
    applicableLaw:
      "PD-1586: Environmental Compliance Certificate (ECC) Conditionalities",
    conditionId: "PD-1586-2",
    conditionNumber: "",
    complianceRequirement: "Provide EIS document",
    compliant: "N/A",
    remarks: "",
    category: "Documentation",
    priority: "High",
    lawCitation: "",
  },
  {
    // TOXIC SUBSTANCE
    lawId: "RA-6969",
    applicableLaw:
      "RA 6969: Toxic Substances and Hazardous and Nuclear Waste Control Act",
    conditionId: "RA-6969-PCL-1",
    lawCitation: "Priority Chemical List",
    complianceRequirement: "Valid PCL Compliance Certificate",
    compliant: "N/A",
    remarks: "",
    category: "Certification",
    priority: "High",
  },
  {
    lawId: "RA-6969",
    applicableLaw:
      "RA 6969: Toxic Substances and Hazardous and Nuclear Waste Control Act",
    conditionId: "RA-6969-PCL-2",
    lawCitation: "Priority Chemical List",
    complianceRequirement: "Annual Reporting",
    compliant: "N/A",
    remarks: "",
    category: "Reporting",
    priority: "Medium",
  },
  {
    //HARRY START
    lawId: "RA-6969",
    applicableLaw:
      "RA 6969: Toxic Substances and Hazardous and Nuclear Waste Control Act",
    conditionId: "RA-6969-CCO-1",
    lawCitation: "Chemical Control Order",
    complianceRequirement:
      "Biennial Report for those chemicals that are for issuance of CCO",
    compliant: "N/A",
    remarks: "",
    category: "Reporting",
    priority: "Medium",
  },
  {
    lawId: "RA-6969",
    applicableLaw:
      "RA 6969: Toxic Substances and Hazardous and Nuclear Waste Control Act",
    conditionId: "RA-6969-CCO-2",
    lawCitation: "Chemical Control Order",
    complianceRequirement: "CCO Registration",
    compliant: "N/A",
    remarks: "",
    category: "Certification",
    priority: "High",
  },
  {
    lawId: "RA-6969",
    applicableLaw:
      "RA 6969: Toxic Substances and Hazardous and Nuclear Waste Control Act",
    conditionId: "RA-6969-IMP-1",
    lawCitation: "Importation",
    complianceRequirement: "Valid Small Quantity Importation Clearance",
    compliant: "N/A",
    remarks: "",
    category: "Certification",
    priority: "High",
  },
  {
    lawId: "RA-6969",
    applicableLaw:
      "RA 6969: Toxic Substances and Hazardous and Nuclear Waste Control Act",
    conditionId: "RA-6969-IMP-2",
    lawCitation: "Importation",
    complianceRequirement: "Valid Importation Clearance",
    compliant: "N/A",
    remarks: "",
    category: "Certification",
    priority: "High",
  },
  {
    lawId: "RA-6969",
    applicableLaw:
      "RA 6969: Toxic Substances and Hazardous and Nuclear Waste Control Act",
    conditionId: "RA-6969-IMP-3",
    lawCitation: "Importation",
    complianceRequirement: "Bill of Lading",
    compliant: "N/A",
    remarks: "",
    category: "Documentation",
    priority: "Medium",
  },
  {
    lawId: "RA-6969",
    applicableLaw:
      "RA 6969: Toxic Substances and Hazardous and Nuclear Waste Control Act",
    conditionId: "RA-6969-HWG-1",
    lawCitation: "Hazardous Waste Generator",
    complianceRequirement: "Registration as Hazardous Waste Generator",
    compliant: "N/A",
    remarks: "",
    category: "Certification",
    priority: "High",
  },
  {
    lawId: "RA-6969",
    applicableLaw:
      "RA 6969: Toxic Substances and Hazardous and Nuclear Waste Control Act",
    conditionId: "RA-6969-HWG-2",
    lawCitation: "Hazardous Waste Generator",
    complianceRequirement: "With temporary Hazwaste Storage Facility",
    compliant: "N/A",
    remarks: "",
    category: "Operational",
    priority: "Medium",
  },
  {
    lawId: "RA-6969",
    applicableLaw:
      "RA 6969: Toxic Substances and Hazardous and Nuclear Waste Control Act",
    conditionId: "RA-6969-HWSL-1",
    lawCitation: "Hazardous Waste Storage and Labeling",
    complianceRequirement: "Hazardous Waste properly labeled",
    compliant: "N/A",
    remarks: "",
    category: "Operational",
    priority: "Medium",
  },
  {
    lawId: "RA-6969",
    applicableLaw:
      "RA 6969: Toxic Substances and Hazardous and Nuclear Waste Control Act",
    conditionId: "RA-6969-HWSL-2",
    lawCitation: "Hazardous Waste Storage and Labeling",
    complianceRequirement: "Valid Permit to Transport",
    compliant: "N/A",
    remarks: "",
    category: "Permitting",
    priority: "High",
  },
  {
    lawId: "RA-6969",
    applicableLaw:
      "RA 6969: Toxic Substances and Hazardous and Nuclear Waste Control Act",
    conditionId: "RA-6969-HWSL-3",
    lawCitation: "Hazardous Waste Storage and Labeling",
    complianceRequirement: "Valid Registration of Transporter and Treaters",
    compliant: "N/A",
    remarks: "",
    category: "Certification",
    priority: "High",
  },
  {
    lawId: "RA-6969",
    applicableLaw:
      "RA 6969: Toxic Substances and Hazardous and Nuclear Waste Control Act",
    conditionId: "RA-6969-WT-WTR-1",
    lawCitation:
      "Waste Transporter, Waste Transport Record; Waste Treatment and Disposal Premises",
    complianceRequirement:
      "WCompliance with Manifest system (Waste Transport Record)",
    compliant: "N/A",
    remarks: "",
    category: "Operational",
    priority: "Medium",
  },
  {
    lawId: "RA-6969",
    applicableLaw:
      "RA 6969: Toxic Substances and Hazardous and Nuclear Waste Control Act",
    conditionId: "RA-6969-WT-WTR-2",
    lawCitation:
      "Waste Transporter, Waste Transport Record; Waste Treatment and Disposal Premises",
    complianceRequirement: "Valid/Completed Cerfificate of Treatment(COT)",
    compliant: "N/A",
    remarks: "",
    category: "Documentation",
    priority: "Medium",
  },
  {
    //AIR
    lawId: "RA-8749",
    applicableLaw: "sample",
    conditionId: "RA-8749-PO-1",
    lawCitation: "RA 8749: Philippine Clean Air Act",
    complianceRequirement: "With Valid POA",
    compliant: "N/A",
    remarks: "",
    category: "Permitting",
    priority: "High",
  },
  {
    lawId: "RA-8749",
    applicableLaw: "Permit to Operate (Air)",
    conditionId: "RA-8749-PO-2",
    lawCitation: "RA 8749: Philippine Clean Air Act",
    complianceRequirement: "All Emission Sources is Covered by a valid POA",
    compliant: "N/A",
    remarks: "",
    category: "Permitting",
    priority: "High",
  },
  {
    lawId: "RA-8749",
    applicableLaw: "RA 8749: Philippine Clean Air Act",
    conditionId: "RA-8749-PO-3",
    lawCitation: "Permit to Operate (Air)",
    complianceRequirement:
      "POA is displayed in a conspicuous place near the installation",
    compliant: "N/A",
    remarks: "",
    category: "Documentation",
    priority: "Medium",
  },
  {
    lawId: "RA-8749",
    applicableLaw: "RA 8749: Philippine Clean Air Act",
    conditionId: "RA-8749-PO-4",
    lawCitation: "Permit to Operate (Air)",
    complianceRequirement: "All Permit Conditions are complied with",
    compliant: "N/A",
    remarks: "",
    category: "Operational",
    priority: "Medium",
  },
  {
    lawId: "RA-8749",
    applicableLaw: "RA 8749: Philippine Clean Air Act",
    conditionId: "RA-8749-PO-5",
    lawCitation: "Permit to Operate (Air)",
    complianceRequirement: "Wind direction device installed (if applicable)",
    compliant: "N/A",
    remarks: "",
    category: "Operational",
    priority: "Low",
  },
  {
    lawId: "RA-8749",
    applicableLaw: "RA 8749: Philippine Clean Air Act",
    conditionId: "RA-8749-PO-6",
    lawCitation: "Permit to Operate (Air)",
    complianceRequirement:
      "Plant operational problems lasting for more than 1 hour should be reoprted to EMB w/in 24 hrs.",
    compliant: "N/A",
    remarks: "",
    category: "Reporting",
    priority: "Medium",
  },
  {
    lawId: "RA-8749",
    applicableLaw: "RA 8749: Philippine Clean Air Act",
    conditionId: "RA-8749-PO-7",
    lawCitation: "Permit to Operate (Air)",
    complianceRequirement: "CCTV installed (for large sources only)",
    compliant: "N/A",
    remarks: "",
    category: "Operational",
    priority: "Low",
  },
  {
    lawId: "RA-8749",
    applicableLaw: "RA 8749: Philippine Clean Air Act",
    conditionId: "RA-8749-PO-8",
    lawCitation: "Permit to Operate (Air)",
    complianceRequirement:
      "CEMS/PEMS installed (for petroleum refineries, power/cement plants or sources emitting (750Tons/yr.) Yearly RATA/Quarterly CGA conducted (for sources w/CEMS",
    compliant: "N/A",
    remarks: "",
    category: "Monitoring",
    priority: "Medium",
  },
  {
    lawId: "RA-8749",
    applicableLaw: "RA 8749: Philippine Clean Air Act",
    conditionId: "RA-8749-ET-1",
    lawCitation: "Emission Testing (if applicable)",
    complianceRequirement: "Compliance w/ emission standars?",
    compliant: "N/A",
    remarks: "",
    category: "Monitoring",
    priority: "Medium",
  },
  {
    lawId: "RA-8749",
    applicableLaw: "RA 8749: Philippine Clean Air Act",
    conditionId: "RA-8749-AT-1",
    lawCitation: "Ambient Testing (if applicable)",
    complianceRequirement: "Compliance w/ ambient air quality standards?",
    compliant: "N/A",
    remarks: "",
    category: "Monitoring",
    priority: "Medium",
  },
  {
    //WATER
    lawId: "RA-9275",
    applicableLaw: "RA 9275: Philippine Clean Water Act",
    conditionId: "RA-9275-DP-1",
    lawCitation: "Discharge Permit (DP)",
    complianceRequirement: "With Valid Discharge Permit",
    compliant: "N/A",
    remarks: "",
    category: "Permitting",
    priority: "High",
  },
  {
    lawId: "RA-9275",
    applicableLaw: "RA 9275: Philippine Clean Water Act",
    conditionId: "RA-9275-DP-2",
    lawCitation: "Discharge Permit (DP)",
    complianceRequirement: "Volume if Duscgarge consistent with DP issued?",
    compliant: "N/A",
    remarks: "",
    category: "Operational",
    priority: "Medium",
  },
  {
    lawId: "RA-9275",
    applicableLaw: "RA 9275: Philippine Clean Water Act",
    conditionId: "RA-9275-DP-3",
    lawCitation: "Discharge Permit (DP)",
    complianceRequirement: "All permit conditions are complied with?",
    compliant: "N/A",
    remarks: "",
    category: "Operational",
    priority: "Medium",
  },
  {
    lawId: "RA-9275",
    applicableLaw: "RA 9275: Philippine Clean Water Act",
    conditionId: "RA-9275-DP-4",
    lawCitation: "Discharge Permit (DP)",
    complianceRequirement: "With working flow metering device (if applicable)",
    compliant: "N/A",
    remarks: "",
    category: "Operational",
    priority: "Medium",
  },
  {
    lawId: "RA-9275",
    applicableLaw: "RA 9275: Philippine Clean Water Act",
    conditionId: "RA-9275-DP-5",
    lawCitation: "Discharge Permit (DP)",
    complianceRequirement:
      "Certificate of septage siphoning hauled by accredited service provider",
    compliant: "N/A",
    remarks: "",
    category: "Documentation",
    priority: "Medium",
  },
  {
    lawId: "RA-9275",
    applicableLaw: "RA 9275: Philippine Clean Water Act",
    conditionId: "RA-9275-ETR-1",
    lawCitation: "Effluent Testing Report (if applicable)",
    complianceRequirement: "In compliance with effluent standards",
    compliant: "N/A",
    remarks: "",
    category: "Monitoring",
    priority: "Medium",
  },
  {
    lawId: "RA-9275",
    applicableLaw: "RA 9275: Philippine Clean Water Act",
    conditionId: "RA-9275-AWQM-1",
    lawCitation: "Ambient Water Quality Monitoring (if applicable)",
    complianceRequirement: "With ambient water quality monitoring results.",
    compliant: "N/A",
    remarks: "",
    category: "Monitoring",
    priority: "Medium",
  },
  {
    lawId: "RA-9275",
    applicableLaw: "RA 9275: Philippine Clean Water Act",
    conditionId: "RA-9275-WCS-2",
    lawCitation: "Wastewater Charge System (if applicable)",
    complianceRequirement: "Payment of wastewater charges",
    compliant: "N/A",
    remarks: "",
    category: "Operational",
    priority: "Medium",
  },
  {
    //SOLID WASTE
    lawId: "RA-9003",
    applicableLaw: "RA 9003: Ecological Solid Waste Management Act",
    conditionId: "RA-9003-WS-1",
    lawCitation: "Waste Segregation",
    complianceRequirement: "With MRF on site",
    compliant: "N/A",
    remarks: "",
    category: "Operational",
    priority: "Medium",
  },
  {
    lawId: "RA-9003",
    applicableLaw: "RA 9003: Ecological Solid Waste Management Act",
    conditionId: "RA-9003-WS-2",
    lawCitation: "Waste Segregation",
    complianceRequirement:
      "Segregated solid waste collected by LGU or Private Contractor Name of PC:",
    compliant: "N/A",
    remarks: "",
    category: "Operational",
    priority: "Medium",
  },
  {
    lawId: "RA-9003",
    applicableLaw: "RA 9003: Ecological Solid Waste Management Act",
    conditionId: "RA-9003-WS-3",
    lawCitation: "Waste Segregation",
    complianceRequirement: "With composting facility (if applicable)",
    compliant: "N/A",
    remarks: "",
    category: "Operational",
    priority: "Low",
  },
  {
    lawId: "RA-9003",
    applicableLaw: "RA 9003: Ecological Solid Waste Management Act",
    conditionId: "RA-9003-SWD-1",
    lawCitation: "Solid Waste Disposal",
    complianceRequirement: "Residuals are disposed to a SLF",
    compliant: "N/A",
    remarks: "",
    category: "Operational",
    priority: "Medium",
  },
  {
    lawId: "RA-9003",
    applicableLaw: "RA 9003: Ecological Solid Waste Management Act",
    conditionId: "RA-9003-SWD-2",
    lawCitation: "Solid Waste Disposal",
    complianceRequirement: "With MOA/Agreement w/ LGU",
    compliant: "N/A",
    remarks: "",
    category: "Documentation",
    priority: "Medium",
  },
  {
    lawId: "Pollution-Control",
    applicableLaw: "Pollution Control Officer Accreditation",
    conditionId: "PCO-1",
    lawCitation: "DAO 2014-02 or Revised Guidelines on PCO Accreditation",
    complianceRequirement: "With valid PCO accreditation certificate",
    compliant: "N/A",
    remarks: "",
    category: "Certification",
    priority: "High",
  },
  {
    lawId: "Pollution-Control",
    applicableLaw: "Pollution Control Officer Accreditation",
    conditionId: "PCO-2",
    lawCitation: "DAO 2014-02 or Revised Guidelines on PCO Accreditation",
    complianceRequirement: "Managing head w/ 8 hrs. training certificate",
    compliant: "N/A",
    remarks: "",
    category: "Training",
    priority: "Medium",
  },
  {
    lawId: "Self-Monitoring",
    applicableLaw: "Self-Monitoring Report",
    conditionId: "SMR-1",
    lawCitation: "DAO 2003-27",
    complianceRequirement: "Complete and timely submission of SMRs (quarterly)",
    compliant: "N/A",
    remarks: "",
    category: "Reporting",
    priority: "Medium",
  },
  {
    lawId: "Self-Monitoring",
    applicableLaw: "Self-Monitoring Report",
    conditionId: "SMR-2",
    lawCitation: "DAO 2003-27",
    complianceRequirement:
      "Complete and timely submission of CMRs/CMVRs (semi-annualy)",
    compliant: "N/A",
    remarks: "",
    category: "Reporting",
    priority: "Medium",
  },
];

export const getComplianceItemsByLaw = (lawId) => {
  return initialComplianceItems.filter((item) => item.lawId === lawId);
};

export const addPD1586Condition = (existingItems = []) => {
  const nextId = `PD-1586-${
    existingItems.filter((i) => i.lawId === "PD-1586").length + 1
  }`;
  return {
    lawId: "PD-1586",
    applicableLaw:
      "Presidential Decree No. 1586 (Environmental Impact Statement System)",
    conditionId: nextId,
    conditionNumber: "",
    complianceRequirement: "",
    compliant: "No",
    remarks: "",
    category: "Documentation",
    priority: "Medium",
    lawCitation: "",
  };
};

export default initialComplianceItems;
