// Product line options tailored to the establishment's nature of business.
// Extend or adjust these lists as needed to reflect actual program data.

export const PRODUCT_LINES_BY_NATURE = {
  "RESTAURANT/FOOD SERVICE": [
    "BAKED GOODS",
    "BEVERAGES",
    "CANNED GOODS",
    "CATERING MEALS",
    "CONDIMENT MANUFACTURING",
    "DAIRY PRODUCTS",
    "DEHYDRATED FOODS",
    "FROZEN DESSERTS",
    "FROZEN MEALS",
    "FRUIT PRESERVES",
    "GOURMET FOODS",
    "ICE PRODUCTS",
    "MEAT PROCESSING",
    "NOODLE PRODUCTION",
    "PREPARED MEALS",
    "SAUCES & CONDIMENTS",
    "SEAFOOD PROCESSING",
    "SNACKS",
    "SPICE BLENDS",
    "SUGAR CONFECTIONERY",
    "VEGETABLE PROCESSING"
  ],
  "RETAIL/WHOLESALE": [
    "APPLIANCE DISTRIBUTION",
    "AUTOMOTIVE PARTS DEALER",
    "BUILDING MATERIALS",
    "CONSUMER GOODS",
    "DRY GOODS",
    "GROCERY ITEMS",
    "HARDWARE SUPPLIES",
    "HOUSEWARES",
    "INDUSTRIAL SUPPLIES",
    "MEDICAL SUPPLIES",
    "OFFICE SUPPLIES",
    "PACKAGING MATERIALS",
    "PERSONAL CARE PRODUCTS",
    "PHARMACEUTICALS",
    "SAFETY EQUIPMENT",
    "SUPERMARKET GOODS",
    "TEXTILES DISTRIBUTOR",
    "WHOLESALE FOOD PRODUCTS"
  ],
  "MANUFACTURING": [
    "AGRO-CHEMICALS",
    "AIRCRAFT COMPONENTS",
    "AUTOMOTIVE PARTS",
    "AUTOMOTIVE PARTS",
    "BATTERY MANUFACTURING",
    "COMPONENT FABRICATION",
    "CONSTRUCTION MATERIALS",
    "ELECTRONICS",
    "ELECTRONICS PACKAGING",
    "FOOD & BEVERAGE",
    "FURNITURE",
    "GLASS PRODUCTS",
    "HEAVY EQUIPMENT",
    "HOUSEHOLD APPLIANCES",
    "METALWORKS",
    "PAINTS & COATINGS",
    "PLASTICS",
    "PRINTED CIRCUIT BOARDS",
    "RUBBER PRODUCTS",
    "SEMICONDUCTOR DEVICES",
    "TEXTILES",
    "TOOL & DIE",
    "WOOD PRODUCTS"
  ],
  "CONSTRUCTION": [
    "CONCRETE PRODUCTS",
    "CONSTRUCTION CHEMICALS",
    "DRYWALL SYSTEMS",
    "ELECTRICAL CABLES",
    "HVAC SYSTEMS",
    "INSULATION MATERIALS",
    "LIGHTING FIXTURES",
    "MECHANICAL COMPONENTS",
    "METAL FABRICATION",
    "PAINTS & COATINGS",
    "PIPE FITTINGS",
    "PRECAST MATERIALS",
    "ROOFING MATERIALS",
    "STEEL PRODUCTS",
    "WATERPROOFING SYSTEMS",
    "WINDOW & DOOR SYSTEMS"
  ],
  "TRANSPORTATION": [
    "AIRCRAFT MAINTENANCE",
    "AUTOMOTIVE MAINTENANCE",
    "BICYCLE MANUFACTURING",
    "ELECTRIC VEHICLES",
    "FLEET SERVICES",
    "LOGISTICS GOODS",
    "MARINE EQUIPMENT",
    "MOTORCYCLE ASSEMBLY",
    "PUBLIC TRANSPORT COMPONENTS",
    "RAILWAY PARTS",
    "SHIPBUILDING PRODUCTS",
    "TIRE MANUFACTURING"
  ],
  "HEALTHCARE/MEDICAL": [
    "DIAGNOSTIC EQUIPMENT",
    "DISINFECTANTS",
    "DISPOSABLE MEDICAL SUPPLIES",
    "HEALTH SUPPLEMENTS",
    "HOSPITAL FURNISHINGS",
    "MEDICAL SUPPLIES",
    "PHARMACEUTICAL PRODUCTS",
    "REHABILITATION EQUIPMENT",
    "SANITARY PRODUCTS",
    "SURGICAL INSTRUMENTS",
    "VACCINES"
  ],
  "AGRICULTURE/FARMING": [
    "ANIMAL FEED",
    "BIOFERTILIZERS",
    "CROP PROTECTION",
    "FERTILIZERS",
    "FISH FEED",
    "FOOD PROCESSING BY-PRODUCTS",
    "GREENHOUSE SUPPLIES",
    "GRAIN MILLING",
    "HORTICULTURE PRODUCTS",
    "LIVESTOCK PRODUCTS",
    "ORGANIC PRODUCE",
    "POULTRY PRODUCTS",
    "SEEDLING PRODUCTION",
    "SEEDS DISTRIBUTION",
    "SOIL CONDITIONERS"
  ],
  "FISHING/AQUACULTURE": [
    "FRESH SEAFOOD",
    "FROZEN SEAFOOD",
    "MARINE OILS",
    "SMOKED SEAFOOD",
    "VALUE-ADDED SEAFOOD",
    "VALUE-ADDED SEAWEED"
  ],
  "MINING": [
    "AGGREGATES",
    "CEMENT ADDITIVES",
    "MINERAL ORE",
    "PROCESSED MINERALS",
    "QUARRY PRODUCTS"
  ],
  "ENERGY/POWER": [
    "ELECTRICAL COMPONENTS",
    "ENERGY STORAGE SYSTEMS",
    "FUEL PRODUCTS",
    "POWER EQUIPMENT",
    "SOLAR MODULES",
    "WIND TURBINE COMPONENTS"
  ],
  "TELECOMMUNICATIONS": [
    "CABLE ASSEMBLIES",
    "FIBER OPTIC EQUIPMENT",
    "ICT INFRASTRUCTURE",
    "NETWORK EQUIPMENT",
    "SATELLITE COMPONENTS",
    "TELECOM DEVICES",
    "WIRELESS DEVICES"
  ],
  "INFORMATION TECHNOLOGY": [
    "COMPUTER ACCESSORIES",
    "COMPUTER HARDWARE",
    "DATA STORAGE DEVICES",
    "ELECTRONIC DEVICES",
    "EMBEDDED SYSTEMS",
    "IT PERIPHERALS",
    "SOFTWARE MEDIA",
    "WEARABLE TECHNOLOGY"
  ],
  "WASTE MANAGEMENT": [
    "E-WASTE PROCESSING",
    "HAZARDOUS WASTE TREATMENT",
    "MEDICAL WASTE PROCESSING",
    "RECYCLABLE MATERIALS",
    "SLUDGE MANAGEMENT",
    "WASTE PROCESSING",
    "WASTE-TO-ENERGY PRODUCTS"
  ],
  "WATER SUPPLY": [
    "BOTTLED WATER",
    "DESALINATION EQUIPMENT",
    "WATER DISTRIBUTION COMPONENTS",
    "WATER TREATMENT CHEMICALS",
    "WATER TREATMENT PRODUCTS"
  ],
  "GOVERNMENT SERVICES": [
    "DOCUMENT SERVICES",
    "EMERGENCY RESPONSE KITS",
    "PUBLIC SERVICE GOODS",
    "REGULATORY SUPPLIES"
  ],
  "NON-PROFIT/CHARITY": [
    "COMMUNITY RELIEF GOODS",
    "RELIEF GOODS",
    "SOCIAL PROGRAM SUPPLIES",
    "TRAINING MATERIALS"
  ],
  "ENTERTAINMENT/RECREATION": [
    "AUDIO EQUIPMENT",
    "CINEMA EQUIPMENT",
    "EVENT DECOR",
    "EVENT SUPPLIES",
    "GAMING EQUIPMENT",
    "LIGHTING SYSTEMS",
    "RECREATIONAL GOODS",
    "STAGE PRODUCTION EQUIPMENT"
  ],
  "SPORTS/FITNESS": [
    "ATHLETIC FOOTWEAR",
    "FITNESS ACCESSORIES",
    "FITNESS EQUIPMENT",
    "SPORTS APPAREL",
    "SPORTS NUTRITION",
    "TEAM SPORTS EQUIPMENT"
  ],
  "BEAUTY/COSMETICS": [
    "AROMATHERAPY PRODUCTS",
    "COSMETIC ACCESSORIES",
    "COSMETIC PRODUCTS",
    "FRAGRANCE PRODUCTS",
    "HAIR CARE PRODUCTS",
    "PERSONAL CARE PRODUCTS",
    "SKIN CARE PRODUCTS"
  ],
  "AUTOMOTIVE SERVICES": [
    "AUTOMOTIVE ACCESSORIES",
    "AUTOMOTIVE ACCESSORIES",
    "CAR CARE PRODUCTS",
    "GARAGE EQUIPMENT",
    "LUBRICANTS",
    "PETROLEUM PRODUCTS",
    "TIRE RETREADING"
  ],
  "REPAIR SERVICES": [
    "ELECTRONIC REPAIR PARTS",
    "INDUSTRIAL REPAIR PARTS",
    "MECHANICAL PARTS",
    "REMANUFACTURED COMPONENTS"
  ],
  "CLEANING SERVICES": [
    "CLEANING AGENTS",
    "DISINFECTION PRODUCTS",
    "JANITORIAL SUPPLIES",
    "LAUNDRY CHEMICALS",
    "SANITATION SUPPLIES"
  ],
  "SECURITY SERVICES": [
    "ALARM SYSTEMS",
    "CCTV SYSTEMS",
    "SECURITY EQUIPMENT",
    "SECURITY SYSTEM SOFTWARE",
    "UNIFORMS"
  ]
};

export const DEFAULT_PRODUCT_LINE_OPTIONS = [
  "CUSTOM MANUFACTURED GOODS",
  "ENVIRONMENTAL PRODUCTS",
  "INDUSTRIAL MACHINERY",
  "LOGISTICS SERVICES",
  "PACKAGING SERVICES",
  "QUALITY CONTROL SERVICES",
  "RESEARCH SERVICES",
  "TRADING SERVICES",
  "WASTE RECYCLING SERVICES",
  "OTHERS"
];


