# Generated by Django 4.2.17 on 2025-10-22 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
    ]
