# Generated by Django 4.2.17 on 2025-11-19 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Legal Unit', 'Legal Unit'), ('Division Chief', 'Division Chief'), ('Section Chief', 'Section Chief'), ('Unit Head', 'Unit Head'), ('Monitoring Personnel', 'Monitoring Personnel')], help_text='User role', max_length=50)),
                ('report_type', models.CharField(choices=[('user', 'User Report'), ('establishment', 'Establishment Report'), ('law', 'Law Report'), ('quota', 'Quota Report'), ('billing', 'Billing Report'), ('compliance', 'Compliance Report'), ('non_compliant', 'Non-Compliant Report'), ('inspection', 'Inspection Report')], help_text='Report type code', max_length=50)),
                ('display_name', models.CharField(blank=True, help_text='Human-readable report name', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Report Access',
                'verbose_name_plural': 'Report Access Rules',
                'ordering': ['role', 'report_type'],
                'indexes': [models.Index(fields=['role'], name='reports_rep_role_2da129_idx'), models.Index(fields=['report_type'], name='reports_rep_report__216dca_idx')],
                'unique_together': {('role', 'report_type')},
            },
        ),
    ]
