# Generated by Django 4.2.17 on 2025-10-22 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inspections', '0012_compliancequota'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0002_auto_20251023_0256'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccomplishmentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Report title', max_length=255)),
                ('report_type', models.CharField(choices=[('quarterly', 'Quarterly Report'), ('monthly', 'Monthly Report'), ('annual', 'Annual Report'), ('custom', 'Custom Period')], default='quarterly', max_length=20)),
                ('quarter', models.IntegerField(choices=[(1, 'Q1'), (2, 'Q2'), (3, 'Q3'), (4, 'Q4')], default=1, help_text='Quarter number')),
                ('year', models.IntegerField(default=2024, help_text='Year of the report')),
                ('period_start', models.DateField(help_text='Start date of the reporting period')),
                ('period_end', models.DateField(help_text='End date of the reporting period')),
                ('summary', models.TextField(help_text='Executive summary of accomplishments')),
                ('key_achievements', models.TextField(help_text='Key achievements during the period')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_inspections', models.ManyToManyField(blank=True, help_text='Inspections included in this report', to='inspections.inspection')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Accomplishment Report',
                'verbose_name_plural': 'Accomplishment Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_inspections', models.IntegerField(default=0)),
                ('compliant_inspections', models.IntegerField(default=0)),
                ('non_compliant_inspections', models.IntegerField(default=0)),
                ('compliance_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('by_law_stats', models.JSONField(default=dict, help_text='Statistics by law type')),
                ('by_district_stats', models.JSONField(default=dict, help_text='Statistics by district')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='reports.accomplishmentreport')),
            ],
            options={
                'verbose_name': 'Report Metric',
                'verbose_name_plural': 'Report Metrics',
            },
        ),
    ]
