# Generated by Django 4.2.17 on 2025-10-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_add_pdf_file_and_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accomplishmentreport',
            name='key_achievements',
            field=models.TextField(blank=True, help_text='Key achievements during the period', null=True),
        ),
        migrations.AlterField(
            model_name='accomplishmentreport',
            name='summary',
            field=models.TextField(blank=True, help_text='Executive summary of accomplishments', null=True),
        ),
    ]
