# Generated by Django 4.2.17 on 2025-11-20 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_reportaccess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportaccess',
            name='report_type',
            field=models.CharField(choices=[('user', 'User Report'), ('establishment', 'Establishment Report'), ('law', 'Law Report'), ('quota', 'Quota Report'), ('billing', 'Billing Report'), ('compliance', 'Compliance Report'), ('non_compliant', 'Non-Compliant Report'), ('inspection', 'Inspection Report'), ('section_accomplishment', 'Section Accomplishment Report'), ('unit_accomplishment', 'Unit Accomplishment Report'), ('monitoring_accomplishment', 'Monitoring Accomplishment Report')], help_text='Report type code', max_length=50),
        ),
    ]
