# Generated by Django 4.2.17 on 2025-11-13 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_user', 'New User Registration'), ('new_establishment', 'New Establishment Created'), ('password_reset', 'Password Reset Request'), ('new_inspection', 'New Inspection Assignment'), ('COMPLIANCE_EXPIRED', 'Compliance Deadline Expired'), ('NOV_SENT', 'Notice of Violation Sent'), ('NOO_SENT', 'Notice of Order Sent'), ('INSPECTION_COMPLETED', 'Inspection Completed'), ('inspection_completed', 'Inspection Completed'), ('inspection_review', 'Inspection Review Required'), ('inspection_forward', 'Inspection Forwarded'), ('reinspection_reminder', 'Reinspection Reminder')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('related_object_type', models.CharField(blank=True, help_text='Type of related object (e.g., inspection, establishment)', max_length=50)),
                ('related_object_id', models.IntegerField(blank=True, help_text='ID of related object', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
