# Generated by Django 4.2.17 on 2025-10-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_user', 'New User Registration'), ('new_establishment', 'New Establishment Created'), ('password_reset', 'Password Reset Request'), ('new_inspection', 'New Inspection Assignment')], max_length=20),
        ),
    ]
