# Generated by Django 4.2.17 on 2025-11-15 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_user', 'New User Registration'), ('new_establishment', 'New Establishment Created'), ('password_reset', 'Password Reset Request'), ('new_inspection', 'New Inspection Assignment'), ('COMPLIANCE_EXPIRED', 'Compliance Deadline Expired'), ('COMPLIANCE_REMINDER', 'Compliance Deadline Reminder'), ('NOV_SENT', 'Notice of Violation Sent'), ('NOO_SENT', 'Notice of Order Sent'), ('INSPECTION_COMPLETED', 'Inspection Completed'), ('inspection_completed', 'Inspection Completed'), ('inspection_review', 'Inspection Review Required'), ('inspection_forward', 'Inspection Forwarded'), ('reinspection_reminder', 'Reinspection Reminder')], max_length=30),
        ),
    ]
