# Generated by Django 4.2.17 on 2025-10-18 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_object_id',
            field=models.IntegerField(blank=True, help_text='ID of related object', null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_object_type',
            field=models.CharField(blank=True, help_text='Type of related object (e.g., inspection, establishment)', max_length=50),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_user', 'New User Registration'), ('new_establishment', 'New Establishment Created'), ('password_reset', 'Password Reset Request'), ('new_inspection', 'New Inspection Assignment'), ('COMPLIANCE_EXPIRED', 'Compliance Deadline Expired'), ('NOV_SENT', 'Notice of Violation Sent'), ('NOO_SENT', 'Notice of Order Sent'), ('INSPECTION_COMPLETED', 'Inspection Completed')], max_length=30),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_a972ce_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', '-created_at'], name='notificatio_user_id_05b4bc_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['related_object_type', 'related_object_id'], name='notificatio_related_f82ec2_idx'),
        ),
    ]
