# Generated by Django 4.2.17 on 2025-11-13 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackupRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(help_text='Backup filename in format backup_YYYYMMDD_HHMMSS.sql', max_length=255, unique=True)),
                ('location', models.CharField(help_text='Full directory path where backup is stored', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When backup was created')),
                ('backup_type', models.CharField(choices=[('backup', 'Backup'), ('restore', 'Restore')], default='backup', help_text='Type of record: backup or restore', max_length=10)),
                ('restored_from', models.ForeignKey(blank=True, help_text='Reference to original backup if this is a restore log entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restore_logs', to='system.backuprecord')),
            ],
            options={
                'verbose_name': 'Backup Record',
                'verbose_name_plural': 'Backup Records',
                'ordering': ['-created_at'],
            },
        ),
    ]
