# Generated by Django 4.2.17 on 2025-11-02 12:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackupRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(help_text='Backup filename (e.g., backup_YYYYMMDD_HHMMSS.sql)', max_length=255)),
                ('location', models.CharField(help_text='Directory path where backup is stored', max_length=500)),
                ('file_path', models.CharField(help_text='Full file path to the backup file', max_length=1000)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the backup was created')),
                ('restored_at', models.DateTimeField(blank=True, help_text='When the backup was restored (if ever)', null=True)),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
            ],
            options={
                'verbose_name': 'Backup Record',
                'verbose_name_plural': 'Backup Records',
                'ordering': ['-created_at'],
            },
        ),
    ]
