# Generated by Django 4.2.17 on 2025-11-02 14:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backuprecord',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='backuprecord',
            name='file_path',
        ),
        migrations.RemoveField(
            model_name='backuprecord',
            name='file_size',
        ),
        migrations.AddField(
            model_name='backuprecord',
            name='fileName',
            field=models.CharField(default=django.utils.timezone.now, help_text='Backup filename in format backup_YYYYMMDD_HHMMSS.sql', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='backuprecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When backup was created'),
        ),
        migrations.AlterField(
            model_name='backuprecord',
            name='location',
            field=models.CharField(help_text='Full directory path where backup is stored', max_length=500),
        ),
        migrations.AlterField(
            model_name='backuprecord',
            name='restored_at',
            field=models.DateTimeField(blank=True, help_text='When backup was restored', null=True),
        ),
    ]
