# Generated by Django 4.2.17 on 2025-11-17 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Law',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('law_title', models.CharField(help_text='Full title of the law or regulation', max_length=255)),
                ('reference_code', models.CharField(blank=True, help_text='Reference code (e.g., RA 8749, PD-1586)', max_length=100, null=True, unique=True)),
                ('description', models.TextField(help_text="Detailed description of the law's scope and intent")),
                ('category', models.CharField(help_text='Category of the law (e.g., Environmental Impact Assessment)', max_length=100)),
                ('effective_date', models.DateField(help_text='Date when the law became effective')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', help_text='Current status of the law', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Law',
                'verbose_name_plural': 'Laws',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['law_title'], name='laws_law_law_tit_c0389d_idx'), models.Index(fields=['reference_code'], name='laws_law_referen_7fda04_idx'), models.Index(fields=['category'], name='laws_law_categor_3620ef_idx'), models.Index(fields=['status'], name='laws_law_status_26745a_idx'), models.Index(fields=['effective_date'], name='laws_law_effecti_c9ff24_idx')],
            },
        ),
    ]
