# Generated by Django 4.2.17 on 2025-11-13 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('nature_of_business', models.CharField(max_length=255)),
                ('year_established', models.CharField(max_length=4)),
                ('province', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('barangay', models.CharField(max_length=100)),
                ('street_building', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=4)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('polygon', models.JSONField(blank=True, null=True)),
                ('marker_icon', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['name'], name='establishme_name_9f5395_idx'), models.Index(fields=['nature_of_business'], name='establishme_nature__7f0240_idx'), models.Index(fields=['city'], name='establishme_city_6fc21b_idx'), models.Index(fields=['barangay'], name='establishme_baranga_fe31e9_idx')],
            },
        ),
    ]
