# Generated by Django 4.2.17 on 2025-10-14 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='establishment',
            index=models.Index(fields=['name'], name='establishme_name_9f5395_idx'),
        ),
        migrations.AddIndex(
            model_name='establishment',
            index=models.Index(fields=['nature_of_business'], name='establishme_nature__7f0240_idx'),
        ),
        migrations.AddIndex(
            model_name='establishment',
            index=models.Index(fields=['city'], name='establishme_city_6fc21b_idx'),
        ),
        migrations.AddIndex(
            model_name='establishment',
            index=models.Index(fields=['barangay'], name='establishme_baranga_fe31e9_idx'),
        ),
    ]
