# Generated by Django 5.2.5 on 2025-09-13 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishment',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
