# Generated by Django 5.2.5 on 2025-09-13 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0002_alter_establishment_name'),
    ]

    operations = [
    ]
