# Generated by Django 4.2.24 on 2025-10-04 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0005_populate_normalized_establishment_data'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='city',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='city',
            name='province',
        ),
        migrations.RemoveField(
            model_name='establishmentdocument',
            name='establishment',
        ),
        migrations.RemoveField(
            model_name='establishmentdocument',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='establishmenthistory',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='establishmenthistory',
            name='establishment',
        ),
        migrations.RemoveField(
            model_name='establishmentnormalized',
            name='barangay',
        ),
        migrations.RemoveField(
            model_name='establishmentnormalized',
            name='business_type',
        ),
        migrations.RemoveField(
            model_name='establishmentnormalized',
            name='city',
        ),
        migrations.RemoveField(
            model_name='establishmentnormalized',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='establishmentnormalized',
            name='establishment_type',
        ),
        migrations.RemoveField(
            model_name='establishmentnormalized',
            name='province',
        ),
        migrations.RemoveField(
            model_name='establishmentnormalized',
            name='status',
        ),
        migrations.RemoveField(
            model_name='establishmentnormalized',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='Barangay',
        ),
        migrations.DeleteModel(
            name='BusinessType',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='EstablishmentDocument',
        ),
        migrations.DeleteModel(
            name='EstablishmentHistory',
        ),
        migrations.DeleteModel(
            name='EstablishmentNormalized',
        ),
        migrations.DeleteModel(
            name='EstablishmentStatus',
        ),
        migrations.DeleteModel(
            name='EstablishmentType',
        ),
        migrations.DeleteModel(
            name='Province',
        ),
    ]
